export const BLE_DEVICE_MODELS = {
  gen1: {
    '01': {
      name: 'SmartWave Faucets',
      fullNameAllModel: 'ETF80 / EBF85, ETF880 / EBF187',
      type: 'ADSKU',
      version: '01',
      generation: '01',
      models: [
        {
          ETFModel: 'ETF80',
          EBFModel: 'EBF85',
          displayName: 'ETF80 / EBF85',
          image: require('src/assets/images/products/gen1/faucet_etf_80.png'),
          notes: '',
        },
        {
          ETFModel: 'ETF880',
          EBFModel: 'EBF187',
          displayName: 'ETF880 / EBF187',
          image: require('src/assets/images/products/gen1/faucet_etf_880.png'),
          notes: '',
        },
      ],
    },
    '02': {
      name: 'SmartWave Faucets',
      fullNameAllModel: 'ETF610 / EBF615, ETF600 / EBF650',
      type: 'ADSKU',
      version: '02',
      generation: '01',
      models: [
        {
          ETFModel: 'ETF610',
          EBFModel: 'EBF615',
          displayName: 'ETF610 / EBF615',
          image: require('src/assets/images/products/gen1/faucet_etf_610.png'),
          notes: '',
        },
        {
          ETFModel: 'ETF600',
          EBFModel: 'EBF650',
          displayName: 'ETF600 / EBF650',
          image: require('src/assets/images/products/gen1/faucet_etf_600.png'),
          notes: '',
        },
      ],
    },
    '03': {
      name: 'SmartWave Faucets',
      fullNameAllModel: 'ETF660 / EBF665, ETF770 / EBF775',
      type: 'ADSKU',
      version: '03',
      generation: '01',
      models: [
        {
          ETFModel: 'ETF660',
          EBFModel: 'EBF665',
          displayName: 'ETF660 / EBF665',
          image: require('src/assets/images/products/gen1/faucet_etf_660.png'),
          notes: '',
        },
        {
          ETFModel: 'ETF770',
          EBFModel: 'EBF775',
          displayName: 'ETF770 / EBF775',
          image: require('src/assets/images/products/gen1/faucet_etf_770.png'),
          notes: '',
        },
      ],
    },
    '04': {
      name: 'SmartWave Faucets',
      fullNameAllModel: 'ETF700 / EBF700, ETF700S / EBF750S',
      type: 'ADSKU',
      version: '04',
      generation: '01',
      models: [
        {
          ETFModel: 'ETF700',
          EBFModel: 'EBF700',
          displayName: 'ETF700 / EBF700',
          image: require('src/assets/images/products/gen1/faucet_etf_700.png'),
          notes: '',
        },
        {
          ETFModel: 'ETF700S',
          EBFModel: 'EBF750S',
          displayName: 'ETF700S / EBF750S',
          image: require('src/assets/images/products/gen1/faucet_etf_700_s.png'),
          notes: '',
        },
      ],
    },
    '05': {
      name: 'SmartWave Faucets',
      fullNameAllModel: 'ETF500 / EBF550, ETF500S / EBF550S, ETF800 / EBF850',
      type: 'ADSKU',
      version: '05',
      generation: '01',
      models: [
        {
          ETFModel: 'ETF500',
          EBFModel: 'EBF550',
          displayName: 'ETF500 / EBF550',
          image: require('src/assets/images/products/gen1/faucet_etf_500.png'),
          notes: '',
        },
        {
          ETFModel: 'ETF500S',
          EBFModel: 'EBF550S',
          displayName: 'ETF500S / EBF550S',
          image: require('src/assets/images/products/gen1/faucet_etf_500.png'),
          notes: '',
        },
        {
          ETFModel: 'ETF800',
          EBFModel: 'EBF850',
          displayName: 'ETF800 / EBF850',
          image: require('src/assets/images/products/gen1/faucet_etf_800.png'),
          notes: '',
        },
      ],
    },
    '06': {
      name: 'SmartWave Faucets',
      fullNameAllModel: 'ETF410 / EBF415, ETF411 / EBF416',
      type: 'ADSKU',
      version: '06',
      generation: '01',
      models: [
        {
          ETFModel: 'ETF410',
          EBFModel: 'EBF415',
          displayName: 'ETF410 / EBF415',
          image: require('src/assets/images/products/gen1/faucet_etf_410.png'),
          notes: '',
        },
        {
          ETFModel: 'ETF411',
          EBFModel: 'EBF416',
          displayName: 'ETF411 / EBF416',
          image: require('src/assets/images/products/gen1/faucet_etf_411.png'),
          notes: '',
        },
      ],
    },
    '07': {
      name: 'SmartWave Faucets',
      fullNameAllModel: 'ETF420 / EBF425, ETF421 / EBF426',
      type: 'ADSKU',
      version: '07',
      generation: '01',
      models: [
        {
          ETFModel: 'ETF420',
          EBFModel: 'EBF425',
          displayName: 'ETF420 / EBF425',
          image: require('src/assets/images/products/gen1/faucet_etf_420.png'),
          notes: '',
        },
        {
          ETFModel: 'ETF421',
          EBFModel: 'EBF426',
          displayName: 'ETF421 / EBF426',
          image: require('src/assets/images/products/gen1/faucet_etf_421.png'),
          notes: '',
        },
      ],
    },
    empty: {
      name: 'UNKNOWN',
      fullNameAllModel: 'UNKNOWN',
      type: 'ADSKU',
      version: '00',
      generation: '01',
      models: [
        {
          ETFModel: 'UNKNOWN FAUCET',
          EBFModel: 'UNKNOWN FAUCET',
          displayName: 'UNKNOWN FAUCET',
          image: require('src/assets/images/products/empty/1.png'),
          notes: '',
        },
      ],
    },
  },
  gen2: {
    '01': {
      name: 'SmartWave Faucets',
      fullNameAllModel: 'ETF80 / EBF85, ETF880 / EBF187',
      type: 'ADSKU',
      version: '01',
      generation: '02',
      models: [
        {
          ETFModel: 'ETF80',
          EBFModel: 'EBF85',
          displayName: 'ETF80 / EBF85',
          image: require('src/assets/images/products/gen1/faucet_etf_80.png'),
          notes: '',
        },
        {
          ETFModel: 'ETF880',
          EBFModel: 'EBF187',
          displayName: 'ETF880 / EBF187',
          image: require('src/assets/images/products/gen1/faucet_etf_880.png'),
          notes: '',
        },
      ],
    },
    '02': {
      name: 'SmartWave Faucets',
      fullNameAllModel: 'ETF610 / EBF615, ETF600 / EBF650',
      type: 'ADSKU',
      version: '02',
      generation: '02',
      models: [
        {
          ETFModel: 'ETF610',
          EBFModel: 'EBF615',
          displayName: 'ETF610 / EBF615',
          image: require('src/assets/images/products/gen1/faucet_etf_610.png'),
          notes: '',
        },
        {
          ETFModel: 'ETF600',
          EBFModel: 'EBF650',
          displayName: 'ETF600 / EBF650',
          image: require('src/assets/images/products/gen1/faucet_etf_600.png'),
          notes: '',
        },
      ],
    },
    '03': {
      name: 'SmartWave Faucets',
      fullNameAllModel: 'ETF660 / EBF665, ETF770 / EBF775',
      type: 'ADSKU',
      version: '03',
      generation: '02',
      models: [
        {
          ETFModel: 'ETF660',
          EBFModel: 'EBF665',
          displayName: 'ETF660 / EBF665',
          image: require('src/assets/images/products/gen1/faucet_etf_660.png'),
          notes: '',
        },
        {
          ETFModel: 'ETF770',
          EBFModel: 'EBF775',
          displayName: 'ETF770 / EBF775',
          image: require('src/assets/images/products/gen1/faucet_etf_770.png'),
          notes: '',
        },
      ],
    },
    '04': {
      name: 'SmartWave Faucets',
      fullNameAllModel: 'ETF700 / EBF700, ETF700S / EBF750S',
      type: 'ADSKU',
      version: '04',
      generation: '02',
      models: [
        {
          ETFModel: 'ETF700',
          EBFModel: 'EBF700',
          displayName: 'ETF700 / EBF700',
          image: require('src/assets/images/products/gen1/faucet_etf_700.png'),
          notes: '',
        },
        {
          ETFModel: 'ETF700S',
          EBFModel: 'EBF750S',
          displayName: 'ETF700S / EBF750S',
          image: require('src/assets/images/products/gen1/faucet_etf_700_s.png'),
          notes: '',
        },
      ],
    },
    '05': {
      name: 'SmartWave Faucets',
      fullNameAllModel: 'ETF500 / EBF550, ETF500S / EBF550S, ETF800 / EBF850',
      type: 'ADSKU',
      version: '05',
      generation: '02',
      models: [
        {
          ETFModel: 'ETF500',
          EBFModel: 'EBF550',
          displayName: 'ETF500 / EBF550',
          image: require('src/assets/images/products/gen1/faucet_etf_500.png'),
          notes: '',
        },
        {
          ETFModel: 'ETF500S',
          EBFModel: 'EBF550S',
          displayName: 'ETF500S / EBF550S',
          image: require('src/assets/images/products/gen1/faucet_etf_500.png'),
          notes: '',
        },
        {
          ETFModel: 'ETF800',
          EBFModel: 'EBF850',
          displayName: 'ETF800 / EBF850',
          image: require('src/assets/images/products/gen1/faucet_etf_800.png'),
          notes: '',
        },
      ],
    },
    '06': {
      name: 'SmartWave Faucets',
      fullNameAllModel: 'ETF410 / EBF415, ETF411 / EBF416',
      type: 'ADSKU',
      version: '06',
      generation: '02',
      models: [
        {
          ETFModel: 'ETF410',
          EBFModel: 'EBF415',
          displayName: 'ETF410 / EBF415',
          image: require('src/assets/images/products/gen1/faucet_etf_410.png'),
          notes: '',
        },
        {
          ETFModel: 'ETF411',
          EBFModel: 'EBF416',
          displayName: 'ETF411 / EBF416',
          image: require('src/assets/images/products/gen1/faucet_etf_411.png'),
          notes: '',
        },
      ],
    },
    '07': {
      name: 'SmartWave Faucets',
      fullNameAllModel: 'ETF420 / EBF425, ETF421 / EBF426',
      type: 'ADSKU',
      version: '07',
      generation: '02',
      models: [
        {
          ETFModel: 'ETF420',
          EBFModel: 'EBF425',
          displayName: 'ETF420 / EBF425',
          image: require('src/assets/images/products/gen1/faucet_etf_420.png'),
          notes: '',
        },
        {
          ETFModel: 'ETF421',
          EBFModel: 'EBF426',
          displayName: 'ETF421 / EBF426',
          image: require('src/assets/images/products/gen1/faucet_etf_421.png'),
          notes: '',
        },
      ],
    },
    empty: {
      name: 'UNKNOWN',
      fullNameAllModel: 'UNKNOWN',
      type: 'ADSKU',
      version: '00',
      generation: '02',
      models: [
        {
          ETFModel: 'UNKNOWN FAUCET',
          EBFModel: 'UNKNOWN FAUCET',
          displayName: 'UNKNOWN FAUCET',
          image: require('src/assets/images/products/empty/1.png'),
          notes: '',
        },
      ],
    },
  },
  basys: {
    '20': {
      name: 'BASYS/Aquis Faucets',
      fullNameAllModel: 'EFX1XX, EFX2XX, EFX3XX, EFX6XX, EFX8XX',
      type: 'ADSKU',
      version: '20',
      generation: '01',
      models: [
        {
          ETFModel: 'EFX1XX',
          EBFModel: '',
          displayName: 'EFX1XX BASYS High',
          image: require('src/assets/images/products/aquis/aquis_efx_1xx.png'),
          notes: '',
        },
        {
          ETFModel: 'EFX2XX',
          EBFModel: '',
          displayName: 'EFX2XX BASYS Mid',
          image: require('src/assets/images/products/aquis/aquis_efx_2xx.png'),
          notes: '',
        },
        {
          ETFModel: 'EFX3XX',
          EBFModel: '',
          displayName: 'EFX3XX BASYS Low',
          image: require('src/assets/images/products/aquis/aquis_efx_3xx.png'),
          notes: '',
        },
        {
          ETFModel: 'EFX6XX',
          EBFModel: '',
          displayName: 'EFX6XX BASYS Low Integrated Base',
          image: require('src/assets/images/products/aquis/aquis_efx_6xx.png'),
          notes: '',
        },
        {
          ETFModel: 'EFX8XX',
          EBFModel: '',
          displayName: 'EFX8XX BASYS Low Integrated Base',
          image: require('src/assets/images/products/aquis/aquis_efx_8xx.png'),
          notes: '',
        },
      ],
    },
    '21': {
      name: 'BASYS/Aquis Faucets',
      fullNameAllModel: 'EAF100',
      type: 'ADSKU',
      version: '21',
      generation: '01',
      models: [
        {
          ETFModel: 'EAF100',
          EBFModel: '',
          displayName: 'EAF100',
          image: require('src/assets/images/products/aquis/aquis_eaf_100.png'),
          notes: '',
        },
      ],
    },
    '22': {
      name: 'BASYS/Aquis Faucets',
      fullNameAllModel: 'EAF200 ',
      type: 'ADSKU',
      version: '22',
      generation: '01',
      models: [
        {
          ETFModel: 'EAF200 ',
          EBFModel: '',
          displayName: 'EAF200 ',
          image: require('src/assets/images/products/aquis/aquis_eaf_200.png'),
          notes: '',
        },
      ],
    },
    '23': {
      name: 'BASYS/Aquis Faucets',
      fullNameAllModel: 'EAF300 ',
      type: 'ADSKU',
      version: '23',
      generation: '01',
      models: [
        {
          ETFModel: 'EAF300 ',
          EBFModel: '',
          displayName: 'EAF300 ',
          image: require('src/assets/images/products/aquis/aquis_eaf_300.png'),
          notes: '',
        },
      ],
    },
    '24': {
      name: 'BASYS/Aquis Faucets',
      fullNameAllModel: 'EAF700 ',
      type: 'ADSKU',
      version: '24',
      generation: '01',
      models: [
        {
          ETFModel: 'EAF700 ',
          EBFModel: '',
          displayName: 'EAF700 ',
          image: require('src/assets/images/products/aquis/aquis_eaf_700.png'),
          notes: '',
        },
      ],
    },
    empty: {
      name: 'UNKNOWN',
      fullNameAllModel: 'UNKNOWN',
      type: 'ADSKU',
      version: '00',
      generation: '01',
      models: [
        {
          ETFModel: 'UNKNOWN FAUCET',
          EBFModel: 'UNKNOWN FAUCET',
          displayName: 'UNKNOWN FAUCET',
          image: require('src/assets/images/products/empty/1.png'),
          notes: '',
        },
      ],
    },
  },
  flusher: {
    '01': {
      name: 'Flushometer',
      fullNameAllModel: 'SOLIS Closet-1.6 GPF',
      type: 'ADSKU',
      version: '01',
      generation: '01',
      models: [
        {
          ETFModel: 'SOLIS 8111-1.6-BI',
          EBFModel: 'SOLIS RESS-C-1.6-BT',
          displayName: 'SOLIS Closet-1.6 GPF',
          image: require('src/assets/images/products/flusher/flushometer_solis_8111.png'),
          type: 'Closet',
          notes: '',
        },
      ],
    },
    '02': {
      name: 'Flushometer',
      fullNameAllModel: 'SOLIS Closet-1.28 GPF',
      type: 'ADSKU',
      version: '02',
      generation: '01',
      models: [
        {
          ETFModel: 'SOLIS 8111-1.28-BT',
          EBFModel: 'SOLIS RESS-C-1.28-BT',
          displayName: 'SOLIS Closet-1.28 GPF',
          image: require('src/assets/images/products/flusher/flushometer_solis_8111.png'),
          type: 'Closet',
          notes: '',
        },
      ],
    },
    '03': {
      name: 'Flushometer',
      fullNameAllModel: 'SOLIS Closet-1.1 GPF',
      type: 'ADSKU',
      version: '03',
      generation: '01',
      models: [
        {
          ETFModel: 'SOLIS 8111-1.1-BT',
          EBFModel: 'SOLIS RESS-C-1.1-BT',
          displayName: 'SOLIS Closet-1.1 GPF',
          image: require('src/assets/images/products/flusher/flushometer_solis_8111.png'),
          type: 'Closet',
          notes: '',
        },
      ],
    },
    '04': {
      name: 'Flushometer',
      fullNameAllModel: 'G2 Closet-1.6 GPF',
      type: 'ADSKU',
      version: '04',
      generation: '01',
      models: [
        {
          ETFModel: 'G2 8111-1.6- BI',
          EBFModel: 'G2 RESS-C-1.6-BT',
          displayName: 'G2 Closet-1.6 GPF',
          image: require('src/assets/images/products/flusher/flushometer_g2_8111.png'),
          type: 'Closet',
          notes: '',
        },
      ],
    },
    '05': {
      name: 'Flushometer',
      fullNameAllModel: 'G2 Closet- 1.28 GPF',
      type: 'ADSKU',
      version: '05',
      generation: '01',
      models: [
        {
          ETFModel: 'G2 8111-1.28-BT',
          EBFModel: 'G2 RESS-C-1.28-BT',
          displayName: 'G2 Closet- 1.28 GPF',
          image: require('src/assets/images/products/flusher/flushometer_g2_8111.png'),
          type: 'Closet',
          notes: '',
        },
      ],
    },
    '06': {
      name: 'Flushometer',
      fullNameAllModel: 'ECOS Closet-1.28 GPF',
      type: 'ADSKU',
      version: '06',
      generation: '01',
      models: [
        {
          ETFModel: 'ECOS 8111-1.28-BT',
          EBFModel: 'ECOS RESS-C-ВТ',
          displayName: 'ECOS Closet-1.28 GPF',
          image: require('src/assets/images/products/flusher/flushometer_ecos_8111_df.png'),
          type: 'Closet',
          notes: '',
        },
      ],
    },
    '07': {
      name: 'Flushometer',
      fullNameAllModel: 'ECOS Closet-1.1 GPF',
      type: 'ADSKU',
      version: '07',
      generation: '01',
      models: [
        {
          ETFModel: 'ECOS 8111- 1.1-BI',
          EBFModel: 'ECOS RESS-C-1.1-BT',
          displayName: 'ECOS Closet-1.1 GPF',
          image: require('src/assets/images/products/flusher/flushometer_ecos_8111_df.png'),
          type: 'Closet',
          notes: '',
        },
      ],
    },
    '08': {
      name: 'Flushometer',
      fullNameAllModel: 'SOLIS Closet-1.6/1.1 GPF',
      type: 'ADSKU',
      version: '08',
      generation: '01',
      models: [
        {
          ETFModel: 'SOLIS 8111-1.6/1.1-BT',
          EBFModel: 'SOLIS RESS-C-1.6/1.1-BT',
          displayName: 'SOLIS Closet-1.6/1.1 GPF',
          image: require('src/assets/images/products/flusher/flushometer_solis_8111.png'),
          type: 'Closet',
          notes: '',
        },
      ],
    },
    '09': {
      name: 'Flushometer',
      fullNameAllModel: 'ECOS Closet-1.6/1.1 GPF',
      type: 'ADSKU',
      version: '09',
      generation: '01',
      models: [
        {
          ETFModel: 'ECOS 8111-1.6/1.1-BT',
          EBFModel: 'ECOS RESS-C-1.6/1.1-BT',
          displayName: 'ECOS Closet-1.6/1.1 GPF',
          image: require('src/assets/images/products/flusher/flushometer_ecos_8111_df.png'),
          type: 'Closet',
          notes: '',
        },
      ],
    },
    '10': {
      name: 'Flushometer',
      fullNameAllModel: 'SOLIS Urinal-0.125 GPF',
      type: 'ADSKU',
      version: '10',
      generation: '01',
      models: [
        {
          ETFModel: 'SOLIS 8186-0.125-BT',
          EBFModel: 'SOLIS RESS-U-0.125-BT',
          displayName: 'SOLIS Urinal-0.25 GPF',
          image: require('src/assets/images/products/flusher/flushometer_solis_8111.png'),
          type: 'Urinal',
          notes: '',
        },
      ],
    },
    '11': {
      name: 'Flushometer',
      fullNameAllModel: 'SOLIS Urinal-0.25 GPF',
      type: 'ADSKU',
      version: '11',
      generation: '01',
      models: [
        {
          ETFModel: 'SOLIS 8186-0.25-BT',
          EBFModel: 'SOLIS RESS-U-0.25-BT',
          displayName: 'SOLIS Urinal-0.25 GPF',
          image: require('src/assets/images/products/flusher/flushometer_solis_8111.png'),
          type: 'Urinal',
          notes: '',
        },
      ],
    },
    '12': {
      name: 'Flushometer',
      fullNameAllModel: 'SOLIS Urinal-0.5 GPF',
      type: 'ADSKU',
      version: '12',
      generation: '01',
      models: [
        {
          ETFModel: 'SOLIS 8186-0.5-BT',
          EBFModel: 'SOLIS RESS-U-0.5-BT',
          displayName: 'SOLIS Urinal-0.5 GPF',
          image: require('src/assets/images/products/flusher/flushometer_solis_8111.png'),
          type: 'Urinal',
          notes: '',
        },
      ],
    },
    '13': {
      name: 'Flushometer',
      fullNameAllModel: 'SOLIS Urinal-1.0 GPF',
      type: 'ADSKU',
      version: '13',
      generation: '01',
      models: [
        {
          ETFModel: 'SOLIS 8186-1.0-BT',
          EBFModel: 'SOLIS RESS-U-1.0-BT',
          displayName: 'SOLIS Urinal-1.0 GPF',
          image: require('src/assets/images/products/flusher/flushometer_solis_8111.png'),
          type: 'Urinal',
          notes: '',
        },
      ],
    },
    '14': {
      name: 'Flushometer',
      fullNameAllModel: 'ECOS Closet-1.28/1.1 GPF',
      type: 'ADSKU',
      version: '14',
      generation: '01',
      models: [
        {
          ETFModel: 'ECOS 8111-1.28/1.1',
          EBFModel: '',
          displayName: 'ECOS Closet-1.28/1.1 GPF',
          image: require('src/assets/images/products/flusher/flushometer_solis_8111.png'),
          type: 'Closet',
          notes: '',
        },
      ],
    },
    '15': {
      name: 'Flushometer',
      fullNameAllModel: 'G2 Urinal-0.25 GPF',
      type: 'ADSKU',
      version: '15',
      generation: '01',
      models: [
        {
          ETFModel: 'G2 8186-0.25-BT',
          EBFModel: 'SOLIS RESSC-1.6-BT',
          displayName: 'G2 Urinal-0.25 GPF',
          image: require('src/assets/images/products/flusher/flushometer_g2_8111.png'),
          type: 'Urinal',
          notes: '',
        },
      ],
    },
    '16': {
      name: 'Flushometer',
      fullNameAllModel: 'G2 Urinal-0.5GPF',
      type: 'ADSKU',
      version: '16',
      generation: '01',
      models: [
        {
          ETFModel: 'G2 8186-0.5-BI',
          EBFModel: 'G2 RESS-U-0.5-BT',
          displayName: 'G2 Urinal-0.5GPF',
          image: require('src/assets/images/products/flusher/flushometer_g2_8111.png'),
          type: 'Urinal',
          notes: '',
        },
      ],
    },
    '17': {
      name: 'Flushometer',
      fullNameAllModel: 'G2 Urinal-1.0GPF',
      type: 'ADSKU',
      version: '17',
      generation: '01',
      models: [
        {
          ETFModel: 'G2 8186-1.0-BI',
          EBFModel: 'G2 RESS-U-1.0-BT',
          displayName: 'G2 Urinal-1.0GPF',
          image: require('src/assets/images/products/flusher/flushometer_g2_8111.png'),
          type: 'Urinal',
          notes: '',
        },
      ],
    },
    '18': {
      name: 'Flushometer',
      fullNameAllModel: 'ECOS Urinal-0.125 GPF',
      type: 'ADSKU',
      version: '18',
      generation: '01',
      models: [
        {
          ETFModel: 'ECOS 8186-0.125-BT',
          EBFModel: 'ECOS RESS-U-0.125-BT',
          displayName: 'ECOS Urinal-0.125 GPF',
          image: require('src/assets/images/products/flusher/flushometer_ecos_8111_df.png'),
          type: 'Urinal',
          notes: '',
        },
      ],
    },
    '19': {
      name: 'Flushometer',
      fullNameAllModel: 'ECOS Urinal-0.25 GPF',
      type: 'ADSKU',
      version: '19',
      generation: '01',
      models: [
        {
          ETFModel: 'ECOS 8186-0.25-BT',
          EBFModel: 'ECOS RESS-U-0.25-BT',
          displayName: 'ECOS Urinal-0.25 GPF',
          image: require('src/assets/images/products/flusher/flushometer_ecos_8111_df.png'),
          type: 'Urinal',
          notes: '',
        },
      ],
    },
    '20': {
      name: 'Flushometer',
      fullNameAllModel: 'ECOS Urinal-0.5 GPF',
      type: 'ADSKU',
      version: '19',
      generation: '01',
      models: [
        {
          ETFModel: 'ECOS 8186-0.5-BT',
          EBFModel: 'ECOS RESS-U-0.5-BT',
          displayName: 'ECOS Urinal-0.5 GPF',
          image: require('src/assets/images/products/flusher/flushometer_ecos_8111_df.png'),
          type: 'Urinal',
          notes: '',
        },
      ],
    },

    empty: {
      name: 'UNKNOWN',
      fullNameAllModel: 'UNKNOWN',
      type: 'ADSKU',
      version: '00',
      generation: '01',
      models: [
        {
          ETFModel: 'UNKNOWN FAUCET',
          EBFModel: 'UNKNOWN FAUCET',
          displayName: 'UNKNOWN FAUCET',
          image: require('src/assets/images/products/empty/1.png'),
          notes: '',
        },
      ],
    },
  },
  unknown: {
    empty: {
      name: 'UNKNOWN',
      fullNameAllModel: 'UNKNOWN',
      type: 'ADSKU',
      version: '00',
      generation: '02',
      models: [
        {
          ETFModel: 'UNKNOWN FAUCET',
          EBFModel: 'UNKNOWN FAUCET',
          displayName: 'UNKNOWN FAUCET',
          image: require('src/assets/images/products/empty/1.png'),
          notes: '',
        },
      ],
    },
  },
};
