export const BLE_DEVICE_MODELS = {
  gen1: {
    '01': {
      name: 'SmartWave Faucets',
      fullNameAllModel: 'ETF80 / EBF85, ETF880 / EBF187',
      type: 'ADSKU',
      version: '01',
      generation: '01',
      models: [
        {
          ETFModel: 'ETF80',
          EBFModel: 'EBF85',
          displayName: 'ETF80 / EBF85',
          image: require('src/assets/images/products/gen1/faucet_etf_80.png'),
          notes: '',
        },
        {
          ETFModel: 'ETF880',
          EBFModel: 'EBF187',
          displayName: 'ETF880 / EBF187',
          image: require('src/assets/images/products/gen1/faucet_etf_880.png'),
          notes: '',
        },
      ],
    },
    '02': {
      name: 'SmartWave Faucets',
      fullNameAllModel: 'ETF610 / EBF615, ETF600 / EBF650',
      type: 'ADSKU',
      version: '02',
      generation: '01',
      models: [
        {
          ETFModel: 'ETF610',
          EBFModel: 'EBF615',
          displayName: 'ETF610 / EBF615',
          image: require('src/assets/images/products/gen1/faucet_etf_610.png'),
          notes: '',
        },
        {
          ETFModel: 'ETF600',
          EBFModel: 'EBF650',
          displayName: 'ETF600 / EBF650',
          image: require('src/assets/images/products/gen1/faucet_etf_600.png'),
          notes: '',
        },
      ],
    },
    '03': {
      name: 'SmartWave Faucets',
      fullNameAllModel: 'ETF660 / EBF665, ETF770 / EBF775',
      type: 'ADSKU',
      version: '03',
      generation: '01',
      models: [
        {
          ETFModel: 'ETF660',
          EBFModel: 'EBF665',
          displayName: 'ETF660 / EBF665',
          image: require('src/assets/images/products/gen1/faucet_etf_660.png'),
          notes: '',
        },
        {
          ETFModel: 'ETF770',
          EBFModel: 'EBF775',
          displayName: 'ETF770 / EBF775',
          image: require('src/assets/images/products/gen1/faucet_etf_770.png'),
          notes: '',
        },
      ],
    },
    '04': {
      name: 'SmartWave Faucets',
      fullNameAllModel: 'ETF700 / EBF700, ETF700S / EBF750S',
      type: 'ADSKU',
      version: '04',
      generation: '01',
      models: [
        {
          ETFModel: 'ETF700',
          EBFModel: 'EBF700',
          displayName: 'ETF700 / EBF700',
          image: require('src/assets/images/products/gen1/faucet_etf_700.png'),
          notes: '',
        },
        {
          ETFModel: 'ETF700S',
          EBFModel: 'EBF750S',
          displayName: 'ETF700S / EBF750S',
          image: require('src/assets/images/products/gen1/faucet_etf_700_s.png'),
          notes: '',
        },
      ],
    },
    '05': {
      name: 'SmartWave Faucets',
      fullNameAllModel: 'ETF500 / EBF550, ETF500S / EBF550S, ETF800 / EBF850',
      type: 'ADSKU',
      version: '05',
      generation: '01',
      models: [
        {
          ETFModel: 'ETF500',
          EBFModel: 'EBF550',
          displayName: 'ETF500 / EBF550',
          image: require('src/assets/images/products/gen1/faucet_etf_500.png'),
          notes: '',
        },
        {
          ETFModel: 'ETF500S',
          EBFModel: 'EBF550S',
          displayName: 'ETF500S / EBF550S',
          image: require('src/assets/images/products/gen1/faucet_etf_500.png'),
          notes: '',
        },
        {
          ETFModel: 'ETF800',
          EBFModel: 'EBF850',
          displayName: 'ETF800 / EBF850',
          image: require('src/assets/images/products/gen1/faucet_etf_800.png'),
          notes: '',
        },
      ],
    },
    '06': {
      name: 'SmartWave Faucets',
      fullNameAllModel: 'ETF410 / EBF415, ETF411 / EBF416',
      type: 'ADSKU',
      version: '06',
      generation: '01',
      models: [
        {
          ETFModel: 'ETF410',
          EBFModel: 'EBF415',
          displayName: 'ETF410 / EBF415',
          image: require('src/assets/images/products/gen1/faucet_etf_410.png'),
          notes: '',
        },
        {
          ETFModel: 'ETF411',
          EBFModel: 'EBF416',
          displayName: 'ETF411 / EBF416',
          image: require('src/assets/images/products/gen1/faucet_etf_411.png'),
          notes: '',
        },
      ],
    },
    '07': {
      name: 'SmartWave Faucets',
      fullNameAllModel: 'ETF420 / EBF425, ETF421 / EBF426',
      type: 'ADSKU',
      version: '07',
      generation: '01',
      models: [
        {
          ETFModel: 'ETF420',
          EBFModel: 'EBF425',
          displayName: 'ETF420 / EBF425',
          image: require('src/assets/images/products/gen1/faucet_etf_420.png'),
          notes: '',
        },
        {
          ETFModel: 'ETF421',
          EBFModel: 'EBF426',
          displayName: 'ETF421 / EBF426',
          image: require('src/assets/images/products/gen1/faucet_etf_421.png'),
          notes: '',
        },
      ],
    },
    empty: {
      name: 'Unknown Faucet',
      fullNameAllModel: 'Unknown Faucet',
      type: 'ADSKU',
      version: '00',
      generation: '01',
      models: [
        {
          ETFModel: 'Unknown Faucet',
          EBFModel: 'Unknown Faucet',
          displayName: 'Unknown Faucet',
          image: require('src/assets/images/products/empty/1.png'),
          notes: '',
        },
      ],
    },
  },
  gen2: {
    '01': {
      name: 'SmartWave Faucets',
      fullNameAllModel: 'ETF80 / EBF85, ETF880 / EBF187',
      type: 'ADSKU',
      version: '01',
      generation: '02',
      models: [
        {
          ETFModel: 'ETF80',
          EBFModel: 'EBF85',
          displayName: 'ETF80 / EBF85',
          image: require('src/assets/images/products/gen1/faucet_etf_80.png'),
          notes: '',
        },
        {
          ETFModel: 'ETF880',
          EBFModel: 'EBF187',
          displayName: 'ETF880 / EBF187',
          image: require('src/assets/images/products/gen1/faucet_etf_880.png'),
          notes: '',
        },
      ],
    },
    '02': {
      name: 'SmartWave Faucets',
      fullNameAllModel: 'ETF610 / EBF615, ETF600 / EBF650',
      type: 'ADSKU',
      version: '02',
      generation: '02',
      models: [
        {
          ETFModel: 'ETF610',
          EBFModel: 'EBF615',
          displayName: 'ETF610 / EBF615',
          image: require('src/assets/images/products/gen1/faucet_etf_610.png'),
          notes: '',
        },
        {
          ETFModel: 'ETF600',
          EBFModel: 'EBF650',
          displayName: 'ETF600 / EBF650',
          image: require('src/assets/images/products/gen1/faucet_etf_600.png'),
          notes: '',
        },
      ],
    },
    '03': {
      name: 'SmartWave Faucets',
      fullNameAllModel: 'ETF660 / EBF665, ETF770 / EBF775',
      type: 'ADSKU',
      version: '03',
      generation: '02',
      models: [
        {
          ETFModel: 'ETF660',
          EBFModel: 'EBF665',
          displayName: 'ETF660 / EBF665',
          image: require('src/assets/images/products/gen1/faucet_etf_660.png'),
          notes: '',
        },
        {
          ETFModel: 'ETF770',
          EBFModel: 'EBF775',
          displayName: 'ETF770 / EBF775',
          image: require('src/assets/images/products/gen1/faucet_etf_770.png'),
          notes: '',
        },
      ],
    },
    '04': {
      name: 'SmartWave Faucets',
      fullNameAllModel: 'ETF700 / EBF700, ETF700S / EBF750S',
      type: 'ADSKU',
      version: '04',
      generation: '02',
      models: [
        {
          ETFModel: 'ETF700',
          EBFModel: 'EBF700',
          displayName: 'ETF700 / EBF700',
          image: require('src/assets/images/products/gen1/faucet_etf_700.png'),
          notes: '',
        },
        {
          ETFModel: 'ETF700S',
          EBFModel: 'EBF750S',
          displayName: 'ETF700S / EBF750S',
          image: require('src/assets/images/products/gen1/faucet_etf_700_s.png'),
          notes: '',
        },
      ],
    },
    '05': {
      name: 'SmartWave Faucets',
      fullNameAllModel: 'ETF500 / EBF550, ETF500S / EBF550S, ETF800 / EBF850',
      type: 'ADSKU',
      version: '05',
      generation: '02',
      models: [
        {
          ETFModel: 'ETF500',
          EBFModel: 'EBF550',
          displayName: 'ETF500 / EBF550',
          image: require('src/assets/images/products/gen1/faucet_etf_500.png'),
          notes: '',
        },
        {
          ETFModel: 'ETF500S',
          EBFModel: 'EBF550S',
          displayName: 'ETF500S / EBF550S',
          image: require('src/assets/images/products/gen1/faucet_etf_500.png'),
          notes: '',
        },
        {
          ETFModel: 'ETF800',
          EBFModel: 'EBF850',
          displayName: 'ETF800 / EBF850',
          image: require('src/assets/images/products/gen1/faucet_etf_800.png'),
          notes: '',
        },
      ],
    },
    '06': {
      name: 'SmartWave Faucets',
      fullNameAllModel: 'ETF410 / EBF415, ETF411 / EBF416',
      type: 'ADSKU',
      version: '06',
      generation: '02',
      models: [
        {
          ETFModel: 'ETF410',
          EBFModel: 'EBF415',
          displayName: 'ETF410 / EBF415',
          image: require('src/assets/images/products/gen1/faucet_etf_410.png'),
          notes: '',
        },
        {
          ETFModel: 'ETF411',
          EBFModel: 'EBF416',
          displayName: 'ETF411 / EBF416',
          image: require('src/assets/images/products/gen1/faucet_etf_411.png'),
          notes: '',
        },
      ],
    },
    '07': {
      name: 'SmartWave Faucets',
      fullNameAllModel: 'ETF420 / EBF425, ETF421 / EBF426',
      type: 'ADSKU',
      version: '07',
      generation: '02',
      models: [
        {
          ETFModel: 'ETF420',
          EBFModel: 'EBF425',
          displayName: 'ETF420 / EBF425',
          image: require('src/assets/images/products/gen1/faucet_etf_420.png'),
          notes: '',
        },
        {
          ETFModel: 'ETF421',
          EBFModel: 'EBF426',
          displayName: 'ETF421 / EBF426',
          image: require('src/assets/images/products/gen1/faucet_etf_421.png'),
          notes: '',
        },
      ],
    },
    empty: {
      name: 'Unknown Faucet',
      fullNameAllModel: 'Unknown Faucet',
      type: 'ADSKU',
      version: '00',
      generation: '01',
      models: [
        {
          ETFModel: 'Unknown Faucet',
          EBFModel: 'Unknown Faucet',
          displayName: 'Unknown Faucet',
          image: require('src/assets/images/products/empty/1.png'),
          notes: '',
        },
      ],
    },
  },
  gen22: {
    '20': {
      name: 'BASYS/Aquis Faucets',
      fullNameAllModel: 'EFX1XX, EFX2XX, EFX3XX, EFX6XX, EFX8XX',
      type: 'ADSKU',
      version: '20',
      models: [
        {
          ETFModel: 'EFX1XX',
          EBFModel: '',
          displayName: 'EFX1XX BASYS High',
          image: require('src/assets/images/products/gen2/aquis_efx_1xx.png'),
          notes: '',
        },
        {
          ETFModel: 'EFX2XX',
          EBFModel: '',
          displayName: 'EFX2XX BASYS Mid',
          image: require('src/assets/images/products/gen2/aquis_efx_2xx.png'),
          notes: '',
        },
        {
          ETFModel: 'EFX3XX',
          EBFModel: '',
          displayName: 'EFX3XX BASYS Low',
          image: require('src/assets/images/products/gen2/aquis_efx_3xx.png'),
          notes: '',
        },
        {
          ETFModel: 'EFX6XX',
          EBFModel: '',
          displayName: 'EFX6XX BASYS Low Integrated Base',
          image: require('src/assets/images/products/gen2/aquis_efx_6xx.png'),
          notes: '',
        },
        {
          ETFModel: 'EFX8XX',
          EBFModel: '',
          displayName: 'EFX8XX BASYS Low Integrated Base',
          image: require('src/assets/images/products/gen2/aquis_efx_8xx.png'),
          notes: '',
        },
      ],
    },
    '21': {
      name: 'BASYS/Aquis Faucets',
      fullNameAllModel: 'EAF100',
      type: 'ADSKU',
      version: '21',
      models: [
        {
          ETFModel: 'EAF100',
          EBFModel: '',
          displayName: 'EAF100',
          image: require('src/assets/images/products/gen2/aquis_eaf_100.png'),
          notes: '',
        },
      ],
    },
    '22': {
      name: 'BASYS/Aquis Faucets',
      fullNameAllModel: 'EAF200 ',
      type: 'ADSKU',
      version: '22',
      models: [
        {
          ETFModel: 'EAF200 ',
          EBFModel: '',
          displayName: 'EAF200 ',
          image: require('src/assets/images/products/gen2/aquis_eaf_200.png'),
          notes: '',
        },
      ],
    },
    '23': {
      name: 'BASYS/Aquis Faucets',
      fullNameAllModel: 'EAF300 ',
      type: 'ADSKU',
      version: '23',
      models: [
        {
          ETFModel: 'EAF300 ',
          EBFModel: '',
          displayName: 'EAF300 ',
          image: require('src/assets/images/products/gen2/aquis_eaf_300.png'),
          notes: '',
        },
      ],
    },
    '24': {
      name: 'BASYS/Aquis Faucets',
      fullNameAllModel: 'EAF700 ',
      type: 'ADSKU',
      version: '24',
      models: [
        {
          ETFModel: 'EAF700 ',
          EBFModel: '',
          displayName: 'EAF700 ',
          image: require('src/assets/images/products/gen2/aquis_eaf_700.png'),
          notes: '',
        },
      ],
    },
    empty: {
      name: 'Unknown Faucet',
      fullNameAllModel: 'Unknown Faucet',
      type: 'ADSKU',
      version: '00',
      generation: '01',
      models: [
        {
          ETFModel: 'Unknown Faucet',
          EBFModel: 'Unknown Faucet',
          displayName: 'Unknown Faucet',
          image: require('src/assets/images/products/empty/1.png'),
          notes: '',
        },
      ],
    },
  },
  gen3: {},
  gen4: {},
};
