export const BLE_GEN2_GATT_SERVICES = {
  '8de47721-5496-4233-ae45-e4b306fe1180': {
    isPrimary: true,
    name: 'GATT SERVICE: FAUCET DATA',
    deviceID: '00:0B:57:6E:87:31',
    uuid: '8de47721-5496-4233-ae45-e4b306fe1180',
    id: 7,
    characteristics: {
      '8de47721-5496-4233-ae45-e4b306fe1181': {
        uuid: '8de47721-5496-4233-ae45-e4b306fe1181',
        name: 'Device Data Integers',
        size: '275 bytes',
        type: 'string',
        range: null,
        initialValue: null,
        properties: ['R'],
        sloanApp: '',
        remarks: '',
        generation: 'gen2',
        prefix: null,
        postfix: null,
        chunks: [
          {
            meta: [
              {
                name: '0x72',
                size: 1,
                position: 0,
                description:
                  'Byte Position 0: Start Flag, Ox72 signals the start of Integers write payload.',
              },
              {
                name: 'LEN',
                size: 1,
                position: 2,
                description:
                  'Byte Position 1: Integer value for the byte length of the package (includes all header bytes and End Flag).',
              },
              {
                name: '# of IDs',
                size: 1,
                position: 3,
                description:
                  'Byte Position 2: Integer value indicating how many Setting IDs to follow in Package.',
              },
              {
                name: '32',
                size: 1,
                position: 4,
                description:
                  'Byte Position 3: Integer value 32 indicates the Setting Value Size 32 = 32-bit size.',
              },
            ],
            uuidData: [
              {
                size: 5,
                position: 11,
                name: {
                  name: 'Date of last factory reset',
                  size: 1,
                  type: 'uint32_t',
                },
                value: {
                  size: 4,
                  dataFormat: 'Unix timestamp',
                  type: 'uint32_t',
                  range: null,
                  initialValue: 'N/A',
                  properties: ['R', 'W'],
                  whenToUpdate: 'every factory reset',
                  remarks: '',
                  prefix: null,
                  postfix: null,
                  valueFormat: 'YYMMDDHHmm',
                  valueType: 'DateTime',
                  dateFormat: 'YY/MM/DD HH:mm',
                },
              },
              {
                size: 5,
                position: 22,
                name: {
                  name: 'Date of last range change',
                  size: 1,
                  type: 'uint32_t',
                },
                value: {
                  size: 4,
                  dataFormat: 'Unix timestamp',
                  type: 'uint32_t',
                  range: null,
                  initialValue: 'N/A',
                  properties: ['R', 'W'],
                  whenToUpdate: 'every range change',
                  remarks: '',
                  prefix: null,
                  postfix: null,
                  valueFormat: 'YYMMDDHHmm',
                  valueType: 'DateTime',
                  dateFormat: 'YY/MM/DD HH:mm',
                },
              },
              {
                size: 5,
                position: 13,
                name: {
                  name: 'Date of last mode change',
                  size: 1,
                  type: 'uint32_t',
                },
                value: {
                  size: 4,
                  dataFormat: 'Unix timestamp',
                  type: 'uint32_t',
                  range: null,
                  initialValue: 'N/A',
                  properties: ['R', 'W'],
                  whenToUpdate: 'every OD or M change',
                  remarks: '',
                  prefix: null,
                  postfix: null,
                  valueFormat: 'YYMMDDHHmm',
                  valueType: 'DateTime',
                  dateFormat: 'YY/MM/DD HH:mm',
                },
              },
              {
                size: 5,
                position: 14,
                name: {
                  name: 'Date of last meter run time change',
                  size: 1,
                  type: 'uint32_t',
                },
                value: {
                  size: 4,
                  dataFormat: 'Unix timestamp',
                  type: 'uint32_t',
                  range: null,
                  initialValue: 'N/A',
                  properties: ['R', 'W'],
                  whenToUpdate: 'every meter runtime change',
                  remarks: '',
                  prefix: null,
                  postfix: null,
                  valueFormat: 'YYMMDDHHmm',
                  valueType: 'DateTime',
                  dateFormat: 'YY/MM/DD HH:mm',
                },
              },
              {
                size: 5,
                position: 15,
                name: {
                  name: 'Date of last OD timeout change',
                  size: 1,
                  type: 'uint32_t',
                },
                value: {
                  size: 4,
                  dataFormat: 'Unix timestamp',
                  type: 'uint32_t',
                  range: null,
                  initialValue: 'N/A',
                  properties: ['R', 'W'],
                  whenToUpdate: 'every OD runtime change',
                  remarks: '',
                  prefix: null,
                  postfix: null,
                  valueFormat: 'YYMMDDHHmm',
                  valueType: 'DateTime',
                  dateFormat: 'YY/MM/DD HH:mm',
                },
              },
              {
                size: 5,
                position: 16,
                name: {
                  name: 'Date of last flush Enable change',
                  size: 1,
                  type: 'uint32_t',
                },
                value: {
                  size: 4,
                  dataFormat: 'Unix timestamp',
                  type: 'uint32_t',
                  range: null,
                  initialValue: 'N/A',
                  properties: ['R', 'W'],
                  whenToUpdate: 'every flush Enable change',
                  remarks: '',
                  prefix: null,
                  postfix: null,
                  valueFormat: 'YYMMDDHHmm',
                  valueType: 'DateTime',
                  dateFormat: 'YY/MM/DD HH:mm',
                },
              },
              {
                size: 5,
                displayInList: false,
                position: 17,
                name: {
                  name: 'Date of flush mode change',
                  size: 1,
                  type: 'uint32_t',
                },
                value: {
                  size: 4,
                  dataFormat: 'Unix timestamp',
                  type: 'uint32_t',
                  range: null,
                  initialValue: 'N/A',
                  properties: ['R', 'W'],
                  whenToUpdate: 'every flush mode change',
                  remarks: '',
                  prefix: null,
                  postfix: null,
                  valueFormat: 'YYMMDDHHmm',
                  valueType: 'DateTime',
                  dateFormat: 'YY/MM/DD HH:mm',
                },
              },
              {
                size: 5,
                displayInList: false,
                position: 18,
                name: {
                  name: 'Date of flush Temp change',
                  size: 1,
                  type: 'uint32_t',
                },
                value: {
                  size: 4,
                  dataFormat: 'Unix timestamp',
                  type: 'uint32_t',
                  range: null,
                  initialValue: 'N/A',
                  properties: ['R', 'W'],
                  whenToUpdate: 'every flush Temp change',
                  remarks: '',
                  prefix: null,
                  postfix: null,
                  valueFormat: 'YYMMDDHHmm',
                  valueType: 'DateTime',
                  dateFormat: 'YY/MM/DD HH:mm',
                },
              },
              {
                size: 5,
                position: 19,
                name: {
                  name: 'Date of last flush time change',
                  size: 1,
                  type: 'uint32_t',
                },
                value: {
                  size: 4,
                  dataFormat: 'Unix timestamp',
                  type: 'uint32_t',
                  range: null,
                  initialValue: 'N/A',
                  properties: ['R', 'W'],
                  whenToUpdate: 'every flush Time change',
                  remarks: '',
                  prefix: null,
                  postfix: null,
                  valueFormat: 'YYMMDDHHmm',
                  valueType: 'DateTime',
                  dateFormat: 'YY/MM/DD HH:mm',
                },
              },
              {
                size: 5,
                position: 20,
                name: {
                  name: 'Date of last flush interval change',
                  size: 1,
                  type: 'uint32_t',
                },
                value: {
                  size: 4,
                  dataFormat: 'Unix timestamp',
                  type: 'uint32_t',
                  range: null,
                  initialValue: 'N/A',
                  properties: ['R', 'W'],
                  whenToUpdate: 'every flush Interval change',
                  remarks: '',
                  prefix: null,
                  postfix: null,
                  valueFormat: 'YYMMDDHHmm',
                  valueType: 'DateTime',
                  dateFormat: 'YY/MM/DD HH:mm',
                },
              },
              {
                size: 5,
                position: 22,
                name: {
                  name: 'Date of last BD note change',
                  size: 1,
                  type: 'uint32_t',
                },
                value: {
                  size: 4,
                  dataFormat: 'Unix timestamp',
                  type: 'uint32_t',
                  range: null,
                  initialValue: 'N/A',
                  properties: ['R', 'W'],
                  whenToUpdate: 'every BD Note change',
                  remarks: '',
                  prefix: null,
                  postfix: null,
                  valueFormat: 'YYMMDDHHmm',
                  valueType: 'DateTime',
                  dateFormat: 'YY/MM/DD HH:mm',
                },
              },
              {
                size: 5,
                displayInList: false,
                position: 0,
                name: {
                  name: 'Date of Full Name change',
                  size: 1,
                  type: 'uint32_t',
                },
                value: {
                  size: 4,
                  dataFormat: 'Unix timestamp',
                  type: 'uint32_t',
                  range: null,
                  initialValue: 'N/A',
                  properties: ['R', 'W'],
                  whenToUpdate: 'every Full Name change',
                  remarks: '',
                  prefix: null,
                  postfix: null,
                },
              },
              {
                size: 5,
                displayInList: false,
                position: 0,
                name: {
                  name: 'Date of Full Nick change',
                  size: 1,
                  type: 'uint32_t',
                },
                value: {
                  size: 4,
                  dataFormat: 'Unix timestamp',
                  type: 'uint32_t',
                  range: null,
                  initialValue: 'N/A',
                  properties: ['R', 'W'],
                  whenToUpdate: 'every Full Nick change',
                  remarks: '',
                  prefix: null,
                  postfix: null,
                },
              },
              {
                size: 5,
                displayInList: false,
                position: 0,
                name: {
                  name: 'Date of last diagnostic',
                  size: 1,
                  type: 'uint32_t',
                },
                value: {
                  size: 4,
                  dataFormat: 'Unix timestamp',
                  type: 'uint32_t',
                  range: null,
                  initialValue: 'N/A',
                  properties: ['R', 'W'],
                  whenToUpdate: 'every diagnosis',
                  remarks: '',
                  prefix: null,
                  postfix: null,
                },
              },
              {
                size: 5,
                position: 21,
                name: {
                  name: 'Date of last Flow Rate change',
                  size: 1,
                  type: 'uint32_t',
                },
                value: {
                  size: 4,
                  dataFormat: 'Unix timestamp',
                  type: 'uint32_t',
                  range: null,
                  initialValue: 'N/A',
                  properties: ['R', 'W'],
                  whenToUpdate: 'every Flow Rate change',
                  remarks: '',
                  prefix: null,
                  postfix: null,
                  valueFormat: 'YYMMDDHHmm',
                  valueType: 'DateTime',
                  dateFormat: 'YY/MM/DD HH:mm',
                },
              },
              {
                size: 5,
                displayInList: false,
                position: 0,
                name: {
                  name: 'Date of last BLE setting change',
                  size: 1,
                  type: 'uint32_t',
                },
                value: {
                  size: 4,
                  dataFormat: 'Unix timestamp',
                  type: 'uint32_t',
                  range: null,
                  initialValue: 'N/A',
                  properties: ['R', 'W'],
                  whenToUpdate: 'every BLE setting change',
                  remarks: '',
                  prefix: null,
                  postfix: null,
                },
              },
              {
                size: 5,
                displayInList: false,
                position: 0,
                name: {
                  name: 'Remote Water dispense',
                  size: 1,
                  type: 'uint32_t',
                },
                value: {
                  size: 4,
                  dataFormat: 'Number',
                  type: 'uint32_t',
                  range: '0-1',
                  initialValue: 0,
                  properties: ['R', 'W'],
                  whenToUpdate: '',
                  remarks: '',
                  prefix: null,
                  postfix: null,
                },
              },
              {
                size: 5,
                displayInList: false,
                position: 0,
                name: {
                  name: 'Diagnostic Init',
                  size: 1,
                  type: 'uint32_t',
                },
                value: {
                  size: 4,
                  dataFormat: 'Number',
                  type: 'uint32_t',
                  range: '0-1',
                  initialValue: 0,
                  properties: ['R', 'W'],
                  whenToUpdate: 'every diagnosis',
                  remarks: '',
                  prefix: null,
                  postfix: null,
                },
              },
              {
                size: 5,
                displayInList: false,
                position: 0,
                name: {
                  name: 'Factory Reset',
                  size: 1,
                  type: 'uint32_t',
                },
                value: {
                  size: 4,
                  dataFormat: 'Number',
                  type: 'uint32_t',
                  range: '0-1',
                  initialValue: 0,
                  properties: ['R', 'W'],
                  whenToUpdate: 'every time this parameter changes',
                  remarks: '',
                  prefix: null,
                  postfix: null,
                },
              },
              {
                size: 5,
                displayInList: false,
                position: 0,
                name: {
                  name: 'Flow Rate - AD',
                  size: 1,
                  type: 'uint32_t',
                },
                value: {
                  size: 4,
                  dataFormat: 'Number',
                  type: 'uint32_t',
                  range: '19 - 83',
                  initialValue: 0,
                  properties: ['R', 'W'],
                  whenToUpdate: 'every Flow-Rate change',
                  remarks: '',
                  prefix: null,
                  postfix: null,
                },
              },
              {
                size: 5,
                displayInList: false,
                position: 0,
                name: {
                  name: 'Sensor Range',
                  size: 1,
                  type: 'uint32_t',
                },
                value: {
                  size: 4,
                  dataFormat: 'Number',
                  type: 'uint32_t',
                  range: '1-5',
                  initialValue: 0,
                  properties: ['R', 'W'],
                  whenToUpdate: 'every time this parameter changes',
                  remarks: '',
                  prefix: null,
                  postfix: null,
                },
              },
              {
                size: 5,
                displayInList: false,
                position: 0,
                name: {
                  name: 'Mode Selection',
                  size: 1,
                  type: 'uint32_t',
                },
                value: {
                  size: 4,
                  dataFormat: 'Number',
                  type: 'uint32_t',
                  range: '0-1',
                  initialValue: 0,
                  properties: ['R', 'W'],
                  whenToUpdate: 'every time this parameter changes',
                  remarks: '',
                  prefix: null,
                  postfix: null,
                },
              },
              {
                size: 5,
                displayInList: false,
                position: 0,
                name: {
                  name: 'Metered Run-time',
                  size: 1,
                  type: 'uint32_t',
                },
                value: {
                  size: 4,
                  dataFormat: 'Number',
                  type: 'uint32_t',
                  range: '3-120',
                  initialValue: 0,
                  properties: ['R', 'W'],
                  whenToUpdate: 'every time this parameter changes',
                  remarks: '',
                  prefix: null,
                  postfix: null,
                },
              },
              {
                size: 5,
                displayInList: false,
                position: 0,
                name: {
                  name: 'Maximum On-demand Run-time',
                  size: 1,
                  type: 'uint32_t',
                },
                value: {
                  size: 4,
                  dataFormat: 'Number',
                  type: 'uint32_t',
                  range: '3-1200',
                  initialValue: 0,
                  properties: ['R', 'W'],
                  whenToUpdate: 'every time this parameter changes',
                  remarks: '',
                  prefix: null,
                  postfix: null,
                },
              },
              {
                size: 5,
                displayInList: false,
                position: 0,
                name: {
                  name: 'Flush Enable',
                  size: 1,
                  type: 'uint32_t',
                },
                value: {
                  size: 4,
                  dataFormat: 'Number',
                  type: 'uint32_t',
                  range: '0-1',
                  initialValue: 0,
                  properties: ['R', 'W'],
                  whenToUpdate: 'every time this parameter changes',
                  remarks: '',
                  prefix: null,
                  postfix: null,
                },
              },
              {
                size: 5,
                displayInList: false,
                position: 0,
                name: {
                  name: 'Flush Mode',
                  size: 1,
                  type: 'uint32_t',
                },
                value: {
                  size: 4,
                  dataFormat: 'Number',
                  type: 'uint32_t',
                  range: '0-1',
                  initialValue: 0,
                  properties: ['R', 'W'],
                  whenToUpdate: 'every time this parameter changes',
                  remarks: '',
                  prefix: null,
                  postfix: null,
                },
              },
              {
                size: 5,
                displayInList: false,
                position: 0,
                name: {
                  name: 'Flush Min Temperature',
                  size: 1,
                  type: 'uint32_t',
                },
                value: {
                  size: 4,
                  dataFormat: 'Number',
                  type: 'uint32_t',
                  range: '1-65',
                  initialValue: 24,
                  properties: ['R', 'W'],
                  whenToUpdate: 'every time this parameter changes',
                  remarks: '',
                  prefix: null,
                  postfix: null,
                },
              },
              {
                size: 5,
                displayInList: false,
                position: 0,
                name: {
                  name: 'Flush Max Temperature',
                  size: 1,
                  type: 'uint32_t',
                },
                value: {
                  size: 4,
                  dataFormat: 'Number',
                  type: 'uint32_t',
                  range: '1-65',
                  initialValue: 46,
                  properties: ['R', 'W'],
                  whenToUpdate: 'every time this parameter changes',
                  remarks: '',
                  prefix: null,
                  postfix: null,
                },
              },
              {
                size: 5,
                displayInList: false,
                position: 0,
                name: {
                  name: 'Flush Time/Duration (Temp Z1)',
                  size: 1,
                  type: 'uint32_t',
                },
                value: {
                  size: 4,
                  dataFormat: 'Number',
                  type: 'uint32_t',
                  range: '3-180',
                  initialValue: 60,
                  properties: ['R', 'W'],
                  whenToUpdate: 'every time this parameter changes',
                  remarks: '',
                  prefix: null,
                  postfix: null,
                },
              },
              {
                size: 5,
                displayInList: false,
                position: 0,
                name: {
                  name: 'Flush Time/Duration (Temp Z2)',
                  size: 1,
                  type: 'uint32_t',
                },
                value: {
                  size: 4,
                  dataFormat: 'Number',
                  type: 'uint32_t',
                  range: '3-180',
                  initialValue: 90,
                  properties: ['R', 'W'],
                  whenToUpdate: 'every time this parameter changes',
                  remarks: '',
                  prefix: null,
                  postfix: null,
                },
              },
              {
                size: 5,
                displayInList: false,
                position: 0,
                name: {
                  name: 'Flush Time/Duration (Temp Z3)',
                  size: 1,
                  type: 'uint32_t',
                },
                value: {
                  size: 4,
                  dataFormat: 'Number',
                  type: 'uint32_t',
                  range: '3-180',
                  initialValue: 30,
                  properties: ['R', 'W'],
                  whenToUpdate: 'every time this parameter changes',
                  remarks: '',
                  prefix: null,
                  postfix: null,
                },
              },
              {
                size: 5,
                displayInList: false,
                position: 0,
                name: {
                  name: 'Flush interval (Temp Z1)',
                  size: 1,
                  type: 'uint32_t',
                },
                value: {
                  size: 4,
                  dataFormat: 'Number',
                  type: 'uint32_t',
                  range: '2-72',
                  initialValue: 48,
                  properties: ['R', 'W'],
                  whenToUpdate: 'every time this parameter changes',
                  remarks: '',
                  prefix: null,
                  postfix: null,
                },
              },
              {
                size: 5,
                displayInList: false,
                position: 0,
                name: {
                  name: 'Flush interval (Temp Z2)',
                  size: 1,
                  type: 'uint32_t',
                },
                value: {
                  size: 4,
                  dataFormat: 'Number',
                  type: 'uint32_t',
                  range: '2-72',
                  initialValue: 24,
                  properties: ['R', 'W'],
                  whenToUpdate: 'every time this parameter changes',
                  remarks: '',
                  prefix: null,
                  postfix: null,
                },
              },
              {
                size: 5,
                displayInList: false,
                position: 0,
                name: {
                  name: 'Flush interval (Temp Z3)',
                  size: 1,
                  type: 'uint32_t',
                },
                value: {
                  size: 4,
                  dataFormat: 'Number',
                  type: 'uint32_t',
                  range: '2-72',
                  initialValue: 24,
                  properties: ['R', 'W'],
                  whenToUpdate: 'every time this parameter changes',
                  remarks: '',
                  prefix: null,
                  postfix: null,
                },
              },
            ],
          },
          {
            meta: [
              {
                name: '0x72',
                size: 1,
                position: 0,
                description:
                  'Byte Position 0: Start Flag, Ox72 signals the start of Integers write payload.',
              },
              {
                name: 'LEN',
                size: 1,
                position: 2,
                description:
                  'Byte Position 1: Integer value for the byte length of the package (includes all header bytes and End Flag).',
              },
              {
                name: '# of IDs',
                size: 1,
                position: 3,
                description:
                  'Byte Position 2: Integer value indicating how many Setting IDs to follow in Package.',
              },
              {
                name: '32',
                size: 1,
                position: 4,
                description:
                  'Byte Position 3: Integer value 32 indicates the Setting Value Size 32 = 32-bit size.',
              },
            ],
            uuidData: [
              {
                size: 5,
                displayInList: false,
                position: 0,
                name: {
                  name: 'Alert 0 Config',
                  size: 1,
                  type: 'uint32_t',
                },
                value: {
                  size: 4,
                  dataFormat: 'Number',
                  type: 'uint32_t',
                  range: '0-255',
                  initialValue: 0,
                  properties: ['R', 'W'],
                  whenToUpdate: '',
                  remarks: '',
                  prefix: null,
                  postfix: null,
                },
              },
              {
                size: 5,
                displayInList: false,
                position: 0,
                name: {
                  name: 'Alert 3 Config',
                  size: 1,
                  type: 'uint32_t',
                },
                value: {
                  size: 4,
                  dataFormat: 'Number',
                  type: 'uint32_t',
                  range: '0-255',
                  initialValue: 0,
                  properties: ['R', 'W'],
                  whenToUpdate: '',
                  remarks: '',
                  prefix: null,
                  postfix: null,
                },
              },
              {
                size: 5,
                displayInList: false,
                position: 0,
                name: {
                  name: 'Alert 4 Config',
                  size: 1,
                  type: 'uint32_t',
                },
                value: {
                  size: 4,
                  dataFormat: 'Number',
                  type: 'uint32_t',
                  range: '0-255',
                  initialValue: 0,
                  properties: ['R', 'W'],
                  whenToUpdate: '',
                  remarks: '',
                  prefix: null,
                  postfix: null,
                },
              },
              {
                size: 5,
                displayInList: false,
                position: 0,
                name: {
                  name: 'Alert 7 Config',
                  size: 1,
                  type: 'uint32_t',
                },
                value: {
                  size: 4,
                  dataFormat: 'Number',
                  type: 'uint32_t',
                  range: '0-255',
                  initialValue: 0,
                  properties: ['R', 'W'],
                  whenToUpdate: '',
                  remarks: '',
                  prefix: null,
                  postfix: null,
                },
              },
              {
                size: 5,
                displayInList: false,
                position: 0,
                name: {
                  name: 'Alert 8 Config',
                  size: 1,
                  type: 'uint32_t',
                },
                value: {
                  size: 4,
                  dataFormat: 'Number',
                  type: 'uint32_t',
                  range: '0-255',
                  initialValue: 0,
                  properties: ['R', 'W'],
                  whenToUpdate: '',
                  remarks: '',
                  prefix: null,
                  postfix: null,
                },
              },
              {
                size: 5,
                displayInList: false,
                position: 0,
                name: {
                  name: 'Alert 11 Config',
                  size: 1,
                  type: 'uint32_t',
                },
                value: {
                  size: 4,
                  dataFormat: 'Number',
                  type: 'uint32_t',
                  range: '0-255',
                  initialValue: 0,
                  properties: ['R', 'W'],
                  whenToUpdate: '',
                  remarks: '',
                  prefix: null,
                  postfix: null,
                },
              },
              {
                size: 5,
                displayInList: false,
                position: 0,
                name: {
                  name: 'Alert 12 Config',
                  size: 1,
                  type: 'uint32_t',
                },
                value: {
                  size: 4,
                  dataFormat: 'Number',
                  type: 'uint32_t',
                  range: '0-255',
                  initialValue: 0,
                  properties: ['R', 'W'],
                  whenToUpdate: '',
                  remarks: '',
                  prefix: null,
                  postfix: null,
                },
              },
              {
                size: 5,
                displayInList: false,
                position: 0,
                name: {
                  name: 'Alert 150 Config',
                  size: 1,
                  type: 'uint32_t',
                },
                value: {
                  size: 4,
                  dataFormat: 'Number',
                  type: 'uint32_t',
                  range: '0-255',
                  initialValue: 0,
                  properties: ['R', 'W'],
                  whenToUpdate: '',
                  remarks: '',
                  prefix: null,
                  postfix: null,
                },
              },
              {
                size: 5,
                displayInList: false,
                position: 0,
                name: {
                  name: 'BLE Mode',
                  size: 1,
                  type: 'uint32_t',
                },
                value: {
                  size: 4,
                  dataFormat: 'Number',
                  type: 'uint32_t',
                  range: '0-1',
                  initialValue: 0,
                  properties: ['R', 'W'],
                  whenToUpdate: '',
                  remarks: '',
                  prefix: null,
                  postfix: null,
                },
              },
              {
                size: 5,
                displayInList: false,
                position: 0,
                name: {
                  name: 'BLE Tx Power',
                  size: 1,
                  type: 'uint32_t',
                },
                value: {
                  size: 4,
                  dataFormat: 'Number',
                  type: 'uint32_t',
                  range: '0-5',
                  initialValue: 0,
                  properties: ['R', 'W'],
                  whenToUpdate: '',
                  remarks: '',
                  prefix: null,
                  postfix: null,
                },
              },
              {
                size: 5,
                displayInList: false,
                position: 0,
                name: {
                  name: 'BLE Adv Frequency',
                  size: 1,
                  type: 'uint32_t',
                },
                value: {
                  size: 4,
                  dataFormat: 'Number',
                  type: 'uint32_t',
                  range: '0-65535',
                  initialValue: 0,
                  properties: ['R', 'W'],
                  whenToUpdate: '',
                  remarks: '',
                  prefix: null,
                  postfix: null,
                },
              },
            ],
          },
        ],
      },
      '8de47721-5496-4233-ae45-e4b306fe1182': {
        uuid: '8de47721-5496-4233-ae45-e4b306fe1182',
        name: 'Device Data STRING',
        size: '182 bytes',
        type: 'string',
        range: null,
        initialValue: null,
        properties: ['R'],
        sloanApp: '',
        remarks: '',
        generation: 'gen2',
        prefix: null,
        postfix: null,
        chunks: [
          {
            meta: [
              {
                name: '0x73',
                size: 1,
                position: 0,
                description:
                  'Byte Position 0: Start Flag, Ox72 signals the start of Integers write payload.',
              },
              {
                name: 'LEN',
                size: 1,
                position: 2,
                description:
                  'Byte Position 1: Integer value for the byte length of the package (includes all header bytes and End Flag).',
              },
            ],
            uuidData: [
              {
                size: 13,
                displayInList: false,
                position: 0,
                name: {
                  name: 'AD Serial Number',
                  size: 3,
                  type: 'String',
                },
                value: {
                  size: 10,
                  dataFormat: 'ANNSSSSSSS',
                  type: 'String',
                  range: null,
                  initialValue: 'A000000000',
                  properties: ['R'],
                  whenToUpdate: 'At AD-BD connection',
                  remarks: '',
                  prefix: null,
                  postfix: null,
                },
              },
              {
                size: 13,
                position: 2,
                name: {
                  name: 'BD Serial Number',
                  size: 3,
                  type: 'String',
                },
                value: {
                  size: 10,
                  dataFormat: 'ANNSSSSSSS',
                  type: 'String',
                  range: null,
                  initialValue: 'A000000000',
                  properties: ['R'],
                  whenToUpdate: 'At AD-BD connection',
                  remarks: '',
                  prefix: null,
                  postfix: null,
                },
              },
              {
                size: 9,
                displayInList: false,
                position: 0,
                name: {
                  name: 'AD Manufacturing Date',
                  size: 3,
                  type: 'String',
                },
                value: {
                  size: 6,
                  dataFormat: 'YYMMDD',
                  type: 'String',
                  range: null,
                  initialValue: '700101',
                  properties: ['R'],
                  whenToUpdate: 'At AD-BD connection',
                  remarks: '',
                  prefix: null,
                  postfix: null,
                  valueFormat: 'YYMMDD',
                  valueType: 'Date',
                  dateFormat: 'YY/MM/DD',
                },
              },
              {
                size: 9,
                displayInList: false,
                position: 0,
                name: {
                  name: 'BD Manufacturing Date',
                  size: 3,
                  type: 'String',
                },
                value: {
                  size: 6,
                  dataFormat: 'YYMMDD',
                  type: 'String',
                  range: null,
                  initialValue: '700101',
                  properties: ['R'],
                  whenToUpdate: 'At AD-BD connection',
                  remarks: '',
                  prefix: null,
                  postfix: null,
                  valueFormat: 'YYMMDD',
                  valueType: 'Date',
                  dateFormat: 'YY/MM/DD',
                },
              },
              {
                size: 7,
                position: 0,
                name: {
                  name: 'AD Hardware Version',
                  size: 3,
                  type: 'String',
                },
                value: {
                  size: 4,
                  dataFormat: 'AAaa',
                  type: 'String',
                  range: null,
                  initialValue: '0000',
                  properties: ['R'],
                  whenToUpdate: 'At AD-BD connection',
                  remarks: '',
                  prefix: null,
                  postfix: null,
                },
              },
              {
                size: 7,
                position: 1,
                name: {
                  name: 'AD Firmware Version',
                  size: 3,
                  type: 'String',
                },
                value: {
                  size: 4,
                  dataFormat: 'AAaa',
                  type: 'String',
                  range: null,
                  initialValue: '0000',
                  properties: ['R'],
                  whenToUpdate: 'At AD-BD connection',
                  remarks: '',
                  prefix: null,
                  postfix: null,
                },
              },
              {
                size: 7,
                position: 3,
                name: {
                  name: 'BD Hardware Version',
                  size: 3,
                  type: 'String',
                },
                value: {
                  size: 4,
                  dataFormat: 'AAaa',
                  type: 'String',
                  range: null,
                  initialValue: 'assigned by Tester',
                  properties: ['R'],
                  whenToUpdate: 'At AD-BD connection',
                  remarks: '',
                  prefix: null,
                  postfix: null,
                },
              },
              {
                size: 7,
                position: 4,
                name: {
                  name: 'BD Firmware Version',
                  size: 3,
                  type: 'String',
                },
                value: {
                  size: 4,
                  dataFormat: 'AAaa',
                  type: 'String',
                  range: null,
                  initialValue: 'BDFW hard-coded',
                  properties: ['R'],
                  whenToUpdate: 'At AD-BD connection',
                  remarks: '',
                  prefix: null,
                  postfix: null,
                },
              },
            ],
          },
          {
            meta: [
              {
                name: '0x73',
                size: 1,
                position: 0,
                description:
                  'Byte Position 0: Start Flag, Ox72 signals the start of Integers write payload.',
              },
              {
                name: 'LEN',
                size: 1,
                position: 2,
                description:
                  'Byte Position 1: Integer value for the byte length of the package (includes all header bytes and End Flag).',
              },
            ],
            uuidData: [
              {
                size: 33,
                displayInList: false,
                position: 0,
                name: {
                  name: 'Full Name',
                  size: 3,
                  type: 'String',
                },
                value: {
                  size: 30,
                  dataFormat: '30 characters',
                  type: 'String',
                  range: null,
                  initialValue: '',
                  properties: ['R', 'W'],
                  whenToUpdate: 'every Full Name change',
                  remarks: '',
                  prefix: null,
                  postfix: null,
                },
              },
              {
                size: 9,
                displayInList: false,
                position: 0,
                name: {
                  name: 'Nick Name',
                  size: 3,
                  type: 'String',
                },
                value: {
                  size: 6,
                  dataFormat: '6 characters',
                  type: 'String',
                  range: null,
                  initialValue: '',
                  properties: ['R', 'W'],
                  whenToUpdate: 'every Nickname change',
                  remarks: '',
                  prefix: null,
                  postfix: null,
                },
              },
              {
                size: 123,
                displayInList: false,
                position: 0,
                name: {
                  name: 'BD Note',
                  size: 3,
                  type: 'String',
                },
                value: {
                  size: 120,
                  dataFormat: '120 characters',
                  type: 'String',
                  range: null,
                  initialValue: '',
                  properties: ['R', 'W'],
                  whenToUpdate: 'every BD Note change',
                  remarks:
                    'BD Note 1 (40 bytes), BD Note 2 (40 bytes), BD Note 3 (40 bytes)',
                  prefix: null,
                  postfix: null,
                },
              },
            ],
          },
        ],
      },
      '8de47721-5496-4233-ae45-e4b306fe1183': {
        uuid: '8de47721-5496-4233-ae45-e4b306fe1183',
        name: 'Data Collection Integer',
        size: '182 bytes',
        type: 'string',
        range: null,
        initialValue: null,
        properties: ['R'],
        sloanApp: '',
        remarks: '',
        generation: 'gen2',
        prefix: null,
        postfix: null,
        chunks: [
          {
            meta: [
              {
                name: '0x72',
                size: 1,
                position: 0,
                description:
                  'Byte Position 0: Start Flag, Ox72 signals the start of Integers write payload.',
              },
              {
                name: 'LEN',
                size: 1,
                position: 2,
                description:
                  'Byte Position 1: Integer value for the byte length of the package (includes all header bytes and End Flag).',
              },
              {
                name: '# of IDs',
                size: 1,
                position: 3,
                description:
                  'Byte Position 2: Integer value indicating how many Setting IDs to follow in Package.',
              },
              {
                name: '32',
                size: 1,
                position: 4,
                description:
                  'Byte Position 3: Integer value 32 indicates the Setting Value Size 32 = 32-bit size.',
              },
            ],
            uuidData: [
              {
                size: 5,
                displayInList: false,
                position: 0,
                name: {
                  name: 'AD SKU',
                  size: 1,
                  type: 'uint32_t',
                },
                value: {
                  size: 4,
                  dataFormat: 'Number',
                  type: 'uint32_t',
                  range: '0-256',
                  initialValue: '0',
                  properties: ['R'],
                  whenToUpdate: 'At AD-BD connection',
                  remarks: '',
                  prefix: null,
                  postfix: null,
                },
              },
              {
                size: 5,
                displayInList: false,
                position: 0,
                name: {
                  name: 'BD SKU',
                  size: 1,
                  type: 'uint32_t',
                },
                value: {
                  size: 4,
                  dataFormat: 'Number',
                  type: 'uint32_t',
                  range: '0-256',
                  initialValue: 'BDSKU hard-coded',
                  properties: ['R'],
                  whenToUpdate: 'At AD-BD connection',
                  remarks: '',
                  prefix: null,
                  postfix: null,
                },
              },
              {
                size: 5,
                displayInList: false,
                position: 0,
                name: {
                  name: 'Operating hours since install',
                  size: 1,
                  type: 'uint32_t',
                },
                value: {
                  size: 4,
                  dataFormat: 'Number',
                  type: 'uint32_t',
                  range: '0-256',
                  initialValue: '0',
                  properties: ['R'],
                  whenToUpdate: 'every hour after power-up',
                  remarks:
                    'Use adbd_sku variable which combines both ad_sku and bd_sku',
                  prefix: null,
                  postfix: null,
                },
              },
              {
                size: 5,
                displayInList: false,
                position: 0,
                name: {
                  name: 'Activations since install',
                  size: 1,
                  type: 'uint32_t',
                },
                value: {
                  size: 4,
                  dataFormat: 'Number',
                  type: 'uint32_t',
                  range: '0-256',
                  initialValue: '0',
                  properties: ['R'],
                  whenToUpdate: 'every activation',
                  remarks: '',
                  prefix: null,
                  postfix: null,
                },
              },
              {
                size: 5,
                displayInList: false,
                position: 0,
                name: {
                  name: 'Activations since last change',
                  size: 1,
                  type: 'uint32_t',
                },
                value: {
                  size: 4,
                  dataFormat: 'Number',
                  type: 'uint32_t',
                  range: '0-256',
                  initialValue: '0',
                  properties: ['R'],
                  whenToUpdate: 'every activation',
                  remarks: '',
                  prefix: null,
                  postfix: null,
                },
              },
              {
                size: 5,
                displayInList: false,
                position: 0,
                name: {
                  name: 'Duration of all activations',
                  size: 1,
                  type: 'uint32_t',
                },
                value: {
                  size: 4,
                  dataFormat: 'Number',
                  type: 'uint32_t',
                  range: '0-256',
                  initialValue: '0',
                  properties: ['R'],
                  whenToUpdate: 'every activation',
                  remarks: '',
                  prefix: null,
                  postfix: null,
                },
              },
              {
                size: 5,
                displayInList: false,
                position: 0,
                name: {
                  name: 'Duration of all line flushes',
                  size: 1,
                  type: 'uint32_t',
                },
                value: {
                  size: 4,
                  dataFormat: 'Number',
                  type: 'uint32_t',
                  range: '0-256',
                  initialValue: '0',
                  properties: ['R'],
                  whenToUpdate: 'every flush',
                  remarks: '',
                  prefix: null,
                  postfix: null,
                },
              },
              {
                size: 5,
                displayInList: false,
                position: 0,
                name: {
                  name: 'Number of Line flushes',
                  size: 1,
                  type: 'uint32_t',
                },
                value: {
                  size: 4,
                  dataFormat: 'Number',
                  type: 'uint32_t',
                  range: '0-256',
                  initialValue: '0',
                  properties: ['R'],
                  whenToUpdate: 'every flush',
                  remarks: '',
                  prefix: null,
                  postfix: null,
                },
              },
              {
                size: 5,
                displayInList: false,
                position: 0,
                name: {
                  name: 'Number of setting changes since install',
                  size: 1,
                  type: 'uint32_t',
                },
                value: {
                  size: 4,
                  dataFormat: 'Number',
                  type: 'uint32_t',
                  range: '0-256',
                  initialValue: '0',
                  properties: ['R'],
                  whenToUpdate: 'every setting change',
                  remarks: '',
                  prefix: null,
                  postfix: null,
                },
              },
              {
                size: 5,
                displayInList: false,
                position: 0,
                name: {
                  name: 'Number of BLE connections',
                  size: 1,
                  type: 'uint32_t',
                },
                value: {
                  size: 4,
                  dataFormat: 'Number',
                  type: 'uint32_t',
                  range: '0-256',
                  initialValue: '0',
                  properties: ['R'],
                  whenToUpdate: 'every BLE activation',
                  remarks: '',
                  prefix: null,
                  postfix: null,
                },
              },
              {
                size: 5,
                displayInList: false,
                position: 0,
                name: {
                  name: 'Number of BLE advertisement',
                  size: 1,
                  type: 'uint32_t',
                },
                value: {
                  size: 4,
                  dataFormat: 'Number',
                  type: 'uint32_t',
                  range: '0-256',
                  initialValue: '0',
                  properties: ['R'],
                  whenToUpdate:
                    'every BLE advertisement by 3-hand activation or button',
                  remarks: '',
                  prefix: null,
                  postfix: null,
                },
              },
            ],
          },
        ],
      },
      '8de47721-5496-4233-ae45-e4b306fe1184': {
        uuid: '8de47721-5496-4233-ae45-e4b306fe1184',
        name: 'Real Time Data',
        size: '15 bytes',
        type: 'string',
        range: null,
        initialValue: null,
        properties: ['R'],
        sloanApp: '',
        remarks: '',
        generation: 'gen2',
        prefix: null,
        postfix: null,
        chunks: [
          {
            meta: [
              {
                name: '0x75',
                size: 1,
                position: 0,
                description:
                  'Byte Position 0: Start Flag, Ox72 signals the start of Integers write payload.',
              },
              {
                name: 'LEN',
                size: 1,
                position: 2,
                description:
                  'Byte Position 1: Integer value for the byte length of the package (includes all header bytes and End Flag).',
              },
            ],
            uuidData: [
              {
                size: 5,
                displayInList: false,
                position: 0,
                name: {
                  name: 'Alert Flags',
                  size: 1,
                  type: 'uint32_t',
                },
                value: {
                  size: 1,
                  dataFormat: 'one alert per bit',
                  type: 'uint32_t',
                  range: '0-256',
                  initialValue: '0',
                  properties: ['R'],
                  whenToUpdate: 'Reserved',
                  remarks: 'Alert 8-15',
                  prefix: null,
                  postfix: null,
                },
              },
              {
                size: 5,
                displayInList: false,
                position: 0,
                name: {
                  name: 'Alert Flags',
                  size: 1,
                  type: 'uint32_t',
                },
                value: {
                  size: 1,
                  dataFormat: 'one alert per bit',
                  type: 'uint32_t',
                  range: '0-256',
                  initialValue: '0',
                  properties: ['R'],
                  whenToUpdate: 'Reserved',
                  remarks: 'Alert 8-15',
                  prefix: null,
                  postfix: null,
                },
              },
              {
                size: 5,
                displayInList: false,
                position: 0,
                name: {
                  name: 'Temperature',
                  size: 1,
                  type: 'uint32_t',
                },
                value: {
                  size: 1,
                  dataFormat: 'Number',
                  type: 'uint32_t',
                  range: '0-0xFF',
                  initialValue: 'Latest Read',
                  properties: ['R'],
                  whenToUpdate: 'every measurement',
                  remarks:
                    'measured 5s after each water activation, or every hour if no water activation',
                  prefix: null,
                  postfix: null,
                },
              },
              {
                size: 5,
                displayInList: false,
                position: 0,
                name: {
                  name: 'Battery Level %',
                  size: 1,
                  type: 'uint32_t',
                },
                value: {
                  size: 1,
                  dataFormat: 'Number',
                  type: 'uint32_t',
                  range: '0-0x64',
                  initialValue: 'Latest Read',
                  properties: ['R'],
                  whenToUpdate: 'Reserved',
                  remarks: 'measured every second',
                  prefix: null,
                  postfix: null,
                },
              },
              {
                size: 4,
                displayInList: false,
                position: 0,
                name: {
                  name: 'Water Usage',
                  size: 0,
                  type: 'uint32_t',
                },
                value: {
                  size: 4,
                  dataFormat: 'Number',
                  type: 'uint32_t',
                  range: null,
                  initialValue: '',
                  properties: ['R'],
                  whenToUpdate: '',
                  remarks: '',
                  prefix: null,
                  postfix: null,
                },
              },
              {
                size: 1,
                displayInList: false,
                position: 0,
                name: {
                  name: '0xFF',
                  size: 0,
                  type: 'uint32_t',
                },
                value: {
                  size: 1,
                  dataFormat: 'Number',
                  type: 'uint32_t',
                  range: null,
                  initialValue: '',
                  properties: ['R'],
                  whenToUpdate: '',
                  remarks: '',
                  prefix: null,
                  postfix: null,
                },
              },
              {
                size: 1,
                displayInList: false,
                position: 0,
                name: {
                  name: '0xFF',
                  size: 0,
                  type: 'uint32_t',
                },
                value: {
                  size: 1,
                  dataFormat: 'Number',
                  type: 'uint32_t',
                  range: null,
                  initialValue: '',
                  properties: ['R'],
                  whenToUpdate: '',
                  remarks: '',
                  prefix: null,
                  postfix: null,
                },
              },
              {
                size: 1,
                displayInList: false,
                position: 0,
                name: {
                  name: 'External Power Status',
                  size: 0,
                  type: 'uint32_t',
                },
                value: {
                  size: 1,
                  dataFormat: 'Number',
                  type: 'uint32_t',
                  range: null,
                  initialValue: '',
                  properties: ['R'],
                  whenToUpdate: '',
                  remarks: '',
                  prefix: null,
                  postfix: null,
                },
              },
              {
                size: 1,
                displayInList: false,
                position: 0,
                name: {
                  name: 'Range Change',
                  size: 0,
                  type: 'uint32_t',
                },
                value: {
                  size: 1,
                  dataFormat: 'Number',
                  type: 'uint32_t',
                  range: null,
                  initialValue: '',
                  properties: ['R'],
                  whenToUpdate: '',
                  remarks: '',
                  prefix: null,
                  postfix: null,
                },
              },
              {
                size: 1,
                displayInList: false,
                position: 0,
                name: {
                  name: 'EF',
                  size: 0,
                  type: 'uint32_t',
                },
                value: {
                  size: 1,
                  dataFormat: 'Number',
                  type: 'uint32_t',
                  range: null,
                  initialValue: '',
                  properties: ['R'],
                  whenToUpdate: '',
                  remarks: '',
                  prefix: null,
                  postfix: null,
                },
              },
            ],
          },
        ],
      },
    },
  },
};
