const isObjectEmpty = objectName => {
  if (!objectName) return true;
  if (typeof objectName != 'object') return true;
  // consoleLog("objectName", Object.keys(objectName));
  return (
    Object.keys(objectName).length === 0 && objectName.constructor === Object
  );
};

function addSeparatorInString(str, n, separator = ' ') {
  if (!str) return str;
  var a = [],
    start = 0;
  while (start < str.length) {
    a.push(str.slice(start, start + n));
    start += n;
  }
  return a.join(separator);
}

function hexToDecimal(hex, base = 16) {
  if (!hex) return hex;
  return parseInt(hex, base);
}

const chunk = (arr, size) =>
  Array.from({length: Math.ceil(arr.length / size)}, (v, i) =>
    arr.slice(i * size, i * size + size),
  );

const BLE_GATT_SERVICES = {
  '8de47721-5496-4233-ae45-e4b306fe1180': {
    isPrimary: true,
    name: 'Device Information',
    deviceID: '00:0B:57:6E:87:31',
    uuid: '8de47721-5496-4233-ae45-e4b306fe1180',
    id: 7,
    characteristics: {
      '8de47721-5496-4233-ae45-e4b306fe1181': {
        uuid: '8de47721-5496-4233-ae45-e4b306fe1181',
        name: 'Device Data Integers',
        size: '275 bytes',
        type: 'string',
        range: null,
        initialValue: null,
        properties: ['R'],
        sloanApp: '',
        remarks: '',
        generation: 'gen2',
        prefix: null,
        postfix: null,
        chunks: [
          {
            meta: [
              {
                name: '0x72',
                size: 1,
                position: 0,
                description:
                  'Byte Position 0: Start Flag, Ox72 signals the start of Integers write payload.',
              },
              {
                name: 'LEN',
                size: 1,
                position: 2,
                description:
                  'Byte Position 1: Integer value for the byte length of the package (includes all header bytes and End Flag).',
              },
              {
                name: '# of IDs',
                size: 1,
                position: 3,
                description:
                  'Byte Position 2: Integer value indicating how many Setting IDs to follow in Package.',
              },
              {
                name: '32',
                size: 1,
                position: 4,
                description:
                  'Byte Position 3: Integer value 32 indicates the Setting Value Size 32 = 32-bit size.',
              },
            ],
            uuidData: [
              {
                size: 5,
                displayInList: true,
                position: 0,
                name: {
                  name: 'D/T of last factory reset',
                  size: 1,
                  type: 'uint32_t',
                },
                value: {
                  size: 4,
                  dataFormat: 'Unix timestamp',
                  type: 'uint32_t',
                  range: null,
                  initialValue: 'N/A',
                  properties: ['R', 'W'],
                  whenToUpdate: 'every factory reset',
                  remarks: '',
                  prefix: null,
                  postfix: null,
                },
              },
              {
                size: 5,
                displayInList: true,
                position: 0,
                name: {
                  name: 'D/T of last range change',
                  size: 1,
                  type: 'uint32_t',
                },
                value: {
                  size: 4,
                  dataFormat: 'Unix timestamp',
                  type: 'uint32_t',
                  range: null,
                  initialValue: 'N/A',
                  properties: ['R', 'W'],
                  whenToUpdate: 'every range change',
                  remarks: '',
                  prefix: null,
                  postfix: null,
                },
              },
              {
                size: 5,
                displayInList: true,
                position: 0,
                name: {
                  name: 'D/T of last OD or M change',
                  size: 1,
                  type: 'uint32_t',
                },
                value: {
                  size: 4,
                  dataFormat: 'Unix timestamp',
                  type: 'uint32_t',
                  range: null,
                  initialValue: 'N/A',
                  properties: ['R', 'W'],
                  whenToUpdate: 'every OD or M change',
                  remarks: '',
                  prefix: null,
                  postfix: null,
                },
              },
              {
                size: 5,
                displayInList: true,
                position: 0,
                name: {
                  name: 'D/T of meter runtime change',
                  size: 1,
                  type: 'uint32_t',
                },
                value: {
                  size: 4,
                  dataFormat: 'Unix timestamp',
                  type: 'uint32_t',
                  range: null,
                  initialValue: 'N/A',
                  properties: ['R', 'W'],
                  whenToUpdate: 'every meter runtime change',
                  remarks: '',
                  prefix: null,
                  postfix: null,
                },
              },
              {
                size: 5,
                displayInList: true,
                position: 0,
                name: {
                  name: 'D/T of OD runtime change',
                  size: 1,
                  type: 'uint32_t',
                },
                value: {
                  size: 4,
                  dataFormat: 'Unix timestamp',
                  type: 'uint32_t',
                  range: null,
                  initialValue: 'N/A',
                  properties: ['R', 'W'],
                  whenToUpdate: 'every OD runtime change',
                  remarks: '',
                  prefix: null,
                  postfix: null,
                },
              },
              {
                size: 5,
                displayInList: true,
                position: 0,
                name: {
                  name: 'D/T of flush Enable change',
                  size: 1,
                  type: 'uint32_t',
                },
                value: {
                  size: 4,
                  dataFormat: 'Unix timestamp',
                  type: 'uint32_t',
                  range: null,
                  initialValue: 'N/A',
                  properties: ['R', 'W'],
                  whenToUpdate: 'every flush Enable change',
                  remarks: '',
                  prefix: null,
                  postfix: null,
                },
              },
              {
                size: 5,
                displayInList: true,
                position: 0,
                name: {
                  name: 'D/T of flush mode change',
                  size: 1,
                  type: 'uint32_t',
                },
                value: {
                  size: 4,
                  dataFormat: 'Unix timestamp',
                  type: 'uint32_t',
                  range: null,
                  initialValue: 'N/A',
                  properties: ['R', 'W'],
                  whenToUpdate: 'every flush mode change',
                  remarks: '',
                  prefix: null,
                  postfix: null,
                },
              },
              {
                size: 5,
                displayInList: true,
                position: 0,
                name: {
                  name: 'D/T of flush Temp change',
                  size: 1,
                  type: 'uint32_t',
                },
                value: {
                  size: 4,
                  dataFormat: 'Unix timestamp',
                  type: 'uint32_t',
                  range: null,
                  initialValue: 'N/A',
                  properties: ['R', 'W'],
                  whenToUpdate: 'every flush Temp change',
                  remarks: '',
                  prefix: null,
                  postfix: null,
                },
              },
              {
                size: 5,
                displayInList: true,
                position: 0,
                name: {
                  name: 'D/T of flush Time change',
                  size: 1,
                  type: 'uint32_t',
                },
                value: {
                  size: 4,
                  dataFormat: 'Unix timestamp',
                  type: 'uint32_t',
                  range: null,
                  initialValue: 'N/A',
                  properties: ['R', 'W'],
                  whenToUpdate: 'every flush Time change',
                  remarks: '',
                  prefix: null,
                  postfix: null,
                },
              },
              {
                size: 5,
                displayInList: true,
                position: 0,
                name: {
                  name: 'D/T of flush Interval change',
                  size: 1,
                  type: 'uint32_t',
                },
                value: {
                  size: 4,
                  dataFormat: 'Unix timestamp',
                  type: 'uint32_t',
                  range: null,
                  initialValue: 'N/A',
                  properties: ['R', 'W'],
                  whenToUpdate: 'every flush Interval change',
                  remarks: '',
                  prefix: null,
                  postfix: null,
                },
              },
              {
                size: 5,
                displayInList: true,
                position: 0,
                name: {
                  name: 'D/T of BD Note change',
                  size: 1,
                  type: 'uint32_t',
                },
                value: {
                  size: 4,
                  dataFormat: 'Unix timestamp',
                  type: 'uint32_t',
                  range: null,
                  initialValue: 'N/A',
                  properties: ['R', 'W'],
                  whenToUpdate: 'every BD Note change',
                  remarks: '',
                  prefix: null,
                  postfix: null,
                },
              },
              {
                size: 5,
                displayInList: true,
                position: 0,
                name: {
                  name: 'D/T of Full Name change',
                  size: 1,
                  type: 'uint32_t',
                },
                value: {
                  size: 4,
                  dataFormat: 'Unix timestamp',
                  type: 'uint32_t',
                  range: null,
                  initialValue: 'N/A',
                  properties: ['R', 'W'],
                  whenToUpdate: 'every Full Name change',
                  remarks: '',
                  prefix: null,
                  postfix: null,
                },
              },
              {
                size: 5,
                displayInList: true,
                position: 0,
                name: {
                  name: 'D/T of Full Nick change',
                  size: 1,
                  type: 'uint32_t',
                },
                value: {
                  size: 4,
                  dataFormat: 'Unix timestamp',
                  type: 'uint32_t',
                  range: null,
                  initialValue: 'N/A',
                  properties: ['R', 'W'],
                  whenToUpdate: 'every Full Nick change',
                  remarks: '',
                  prefix: null,
                  postfix: null,
                },
              },
              {
                size: 5,
                displayInList: true,
                position: 0,
                name: {
                  name: 'D/T of last diagnostic',
                  size: 1,
                  type: 'uint32_t',
                },
                value: {
                  size: 4,
                  dataFormat: 'Unix timestamp',
                  type: 'uint32_t',
                  range: null,
                  initialValue: 'N/A',
                  properties: ['R', 'W'],
                  whenToUpdate: 'every diagnosis',
                  remarks: '',
                  prefix: null,
                  postfix: null,
                },
              },
              {
                size: 5,
                displayInList: true,
                position: 0,
                name: {
                  name: 'D/T of last Flow Rate change',
                  size: 1,
                  type: 'uint32_t',
                },
                value: {
                  size: 4,
                  dataFormat: 'Unix timestamp',
                  type: 'uint32_t',
                  range: null,
                  initialValue: 'N/A',
                  properties: ['R', 'W'],
                  whenToUpdate: 'every Flow Rate change',
                  remarks: '',
                  prefix: null,
                  postfix: null,
                },
              },
              {
                size: 5,
                displayInList: true,
                position: 0,
                name: {
                  name: 'D/T of last BLE setting change',
                  size: 1,
                  type: 'uint32_t',
                },
                value: {
                  size: 4,
                  dataFormat: 'Unix timestamp',
                  type: 'uint32_t',
                  range: null,
                  initialValue: 'N/A',
                  properties: ['R', 'W'],
                  whenToUpdate: 'every BLE setting change',
                  remarks: '',
                  prefix: null,
                  postfix: null,
                },
              },
              {
                size: 5,
                displayInList: true,
                position: 0,
                name: {
                  name: 'Remote Water dispense',
                  size: 1,
                  type: 'uint32_t',
                },
                value: {
                  size: 4,
                  dataFormat: 'Number',
                  type: 'uint32_t',
                  range: '0-1',
                  initialValue: 0,
                  properties: ['R', 'W'],
                  whenToUpdate: '',
                  remarks: '',
                  prefix: null,
                  postfix: null,
                },
              },
              {
                size: 5,
                displayInList: true,
                position: 0,
                name: {
                  name: 'Diagnostic Init',
                  size: 1,
                  type: 'uint32_t',
                },
                value: {
                  size: 4,
                  dataFormat: 'Number',
                  type: 'uint32_t',
                  range: '0-1',
                  initialValue: 0,
                  properties: ['R', 'W'],
                  whenToUpdate: 'every diagnosis',
                  remarks: '',
                  prefix: null,
                  postfix: null,
                },
              },
              {
                size: 5,
                displayInList: true,
                position: 0,
                name: {
                  name: 'Factory Reset',
                  size: 1,
                  type: 'uint32_t',
                },
                value: {
                  size: 4,
                  dataFormat: 'Number',
                  type: 'uint32_t',
                  range: '0-1',
                  initialValue: 0,
                  properties: ['R', 'W'],
                  whenToUpdate: 'every time this parameter changes',
                  remarks: '',
                  prefix: null,
                  postfix: null,
                },
              },
              {
                size: 5,
                displayInList: true,
                position: 0,
                name: {
                  name: 'Flow Rate - AD',
                  size: 1,
                  type: 'uint32_t',
                },
                value: {
                  size: 4,
                  dataFormat: 'Number',
                  type: 'uint32_t',
                  range: '19 - 83',
                  initialValue: 0,
                  properties: ['R', 'W'],
                  whenToUpdate: 'every Flow-Rate change',
                  remarks: '',
                  prefix: null,
                  postfix: null,
                },
              },
              {
                size: 5,
                displayInList: true,
                position: 0,
                name: {
                  name: 'Sensor Range',
                  size: 1,
                  type: 'uint32_t',
                },
                value: {
                  size: 4,
                  dataFormat: 'Number',
                  type: 'uint32_t',
                  range: '1-5',
                  initialValue: 0,
                  properties: ['R', 'W'],
                  whenToUpdate: 'every time this parameter changes',
                  remarks: '',
                  prefix: null,
                  postfix: null,
                },
              },
              {
                size: 5,
                displayInList: true,
                position: 0,
                name: {
                  name: 'Mode Selection',
                  size: 1,
                  type: 'uint32_t',
                },
                value: {
                  size: 4,
                  dataFormat: 'Number',
                  type: 'uint32_t',
                  range: '0-1',
                  initialValue: 0,
                  properties: ['R', 'W'],
                  whenToUpdate: 'every time this parameter changes',
                  remarks: '',
                  prefix: null,
                  postfix: null,
                },
              },
              {
                size: 5,
                displayInList: true,
                position: 0,
                name: {
                  name: 'Metered Run-time',
                  size: 1,
                  type: 'uint32_t',
                },
                value: {
                  size: 4,
                  dataFormat: 'Number',
                  type: 'uint32_t',
                  range: '3-120',
                  initialValue: 0,
                  properties: ['R', 'W'],
                  whenToUpdate: 'every time this parameter changes',
                  remarks: '',
                  prefix: null,
                  postfix: null,
                },
              },
              {
                size: 5,
                displayInList: true,
                position: 0,
                name: {
                  name: 'Maximum On-demand Run-time',
                  size: 1,
                  type: 'uint32_t',
                },
                value: {
                  size: 4,
                  dataFormat: 'Number',
                  type: 'uint32_t',
                  range: '3-1200',
                  initialValue: 0,
                  properties: ['R', 'W'],
                  whenToUpdate: 'every time this parameter changes',
                  remarks: '',
                  prefix: null,
                  postfix: null,
                },
              },
              {
                size: 5,
                displayInList: true,
                position: 0,
                name: {
                  name: 'Flush Enable',
                  size: 1,
                  type: 'uint32_t',
                },
                value: {
                  size: 4,
                  dataFormat: 'Number',
                  type: 'uint32_t',
                  range: '0-1',
                  initialValue: 0,
                  properties: ['R', 'W'],
                  whenToUpdate: 'every time this parameter changes',
                  remarks: '',
                  prefix: null,
                  postfix: null,
                },
              },
              {
                size: 5,
                displayInList: true,
                position: 0,
                name: {
                  name: 'Flush Mode',
                  size: 1,
                  type: 'uint32_t',
                },
                value: {
                  size: 4,
                  dataFormat: 'Number',
                  type: 'uint32_t',
                  range: '0-1',
                  initialValue: 0,
                  properties: ['R', 'W'],
                  whenToUpdate: 'every time this parameter changes',
                  remarks: '',
                  prefix: null,
                  postfix: null,
                },
              },
              {
                size: 5,
                displayInList: true,
                position: 0,
                name: {
                  name: 'Flush Min Temperature',
                  size: 1,
                  type: 'uint32_t',
                },
                value: {
                  size: 4,
                  dataFormat: 'Number',
                  type: 'uint32_t',
                  range: '1-65',
                  initialValue: 24,
                  properties: ['R', 'W'],
                  whenToUpdate: 'every time this parameter changes',
                  remarks: '',
                  prefix: null,
                  postfix: null,
                },
              },
              {
                size: 5,
                displayInList: true,
                position: 0,
                name: {
                  name: 'Flush Max Temperature',
                  size: 1,
                  type: 'uint32_t',
                },
                value: {
                  size: 4,
                  dataFormat: 'Number',
                  type: 'uint32_t',
                  range: '1-65',
                  initialValue: 46,
                  properties: ['R', 'W'],
                  whenToUpdate: 'every time this parameter changes',
                  remarks: '',
                  prefix: null,
                  postfix: null,
                },
              },
              {
                size: 5,
                displayInList: true,
                position: 0,
                name: {
                  name: 'Flush Time/Duration (Temp Z1)',
                  size: 1,
                  type: 'uint32_t',
                },
                value: {
                  size: 4,
                  dataFormat: 'Number',
                  type: 'uint32_t',
                  range: '3-180',
                  initialValue: 60,
                  properties: ['R', 'W'],
                  whenToUpdate: 'every time this parameter changes',
                  remarks: '',
                  prefix: null,
                  postfix: null,
                },
              },
              {
                size: 5,
                displayInList: true,
                position: 0,
                name: {
                  name: 'Flush Time/Duration (Temp Z2)',
                  size: 1,
                  type: 'uint32_t',
                },
                value: {
                  size: 4,
                  dataFormat: 'Number',
                  type: 'uint32_t',
                  range: '3-180',
                  initialValue: 90,
                  properties: ['R', 'W'],
                  whenToUpdate: 'every time this parameter changes',
                  remarks: '',
                  prefix: null,
                  postfix: null,
                },
              },
              {
                size: 5,
                displayInList: true,
                position: 0,
                name: {
                  name: 'Flush Time/Duration (Temp Z3)',
                  size: 1,
                  type: 'uint32_t',
                },
                value: {
                  size: 4,
                  dataFormat: 'Number',
                  type: 'uint32_t',
                  range: '3-180',
                  initialValue: 30,
                  properties: ['R', 'W'],
                  whenToUpdate: 'every time this parameter changes',
                  remarks: '',
                  prefix: null,
                  postfix: null,
                },
              },
              {
                size: 5,
                displayInList: true,
                position: 0,
                name: {
                  name: 'Flush interval (Temp Z1)',
                  size: 1,
                  type: 'uint32_t',
                },
                value: {
                  size: 4,
                  dataFormat: 'Number',
                  type: 'uint32_t',
                  range: '2-72',
                  initialValue: 48,
                  properties: ['R', 'W'],
                  whenToUpdate: 'every time this parameter changes',
                  remarks: '',
                  prefix: null,
                  postfix: null,
                },
              },
              {
                size: 5,
                displayInList: true,
                position: 0,
                name: {
                  name: 'Flush interval (Temp Z2)',
                  size: 1,
                  type: 'uint32_t',
                },
                value: {
                  size: 4,
                  dataFormat: 'Number',
                  type: 'uint32_t',
                  range: '2-72',
                  initialValue: 24,
                  properties: ['R', 'W'],
                  whenToUpdate: 'every time this parameter changes',
                  remarks: '',
                  prefix: null,
                  postfix: null,
                },
              },
              {
                size: 5,
                displayInList: true,
                position: 0,
                name: {
                  name: 'Flush interval (Temp Z3)',
                  size: 1,
                  type: 'uint32_t',
                },
                value: {
                  size: 4,
                  dataFormat: 'Number',
                  type: 'uint32_t',
                  range: '2-72',
                  initialValue: 24,
                  properties: ['R', 'W'],
                  whenToUpdate: 'every time this parameter changes',
                  remarks: '',
                  prefix: null,
                  postfix: null,
                },
              },
            ],
          },
          {
            meta: [
              {
                name: '0x72',
                size: 1,
                position: 0,
                description:
                  'Byte Position 0: Start Flag, Ox72 signals the start of Integers write payload.',
              },
              {
                name: 'LEN',
                size: 1,
                position: 2,
                description:
                  'Byte Position 1: Integer value for the byte length of the package (includes all header bytes and End Flag).',
              },
              {
                name: '# of IDs',
                size: 1,
                position: 3,
                description:
                  'Byte Position 2: Integer value indicating how many Setting IDs to follow in Package.',
              },
              {
                name: '32',
                size: 1,
                position: 4,
                description:
                  'Byte Position 3: Integer value 32 indicates the Setting Value Size 32 = 32-bit size.',
              },
            ],
            uuidData: [
              {
                size: 5,
                displayInList: true,
                position: 0,
                name: {
                  name: 'Alert 0 Config',
                  size: 1,
                  type: 'uint32_t',
                },
                value: {
                  size: 4,
                  dataFormat: 'Number',
                  type: 'uint32_t',
                  range: '0-255',
                  initialValue: 0,
                  properties: ['R', 'W'],
                  whenToUpdate: '',
                  remarks: '',
                  prefix: null,
                  postfix: null,
                },
              },
              {
                size: 5,
                displayInList: true,
                position: 0,
                name: {
                  name: 'Alert 3 Config',
                  size: 1,
                  type: 'uint32_t',
                },
                value: {
                  size: 4,
                  dataFormat: 'Number',
                  type: 'uint32_t',
                  range: '0-255',
                  initialValue: 0,
                  properties: ['R', 'W'],
                  whenToUpdate: '',
                  remarks: '',
                  prefix: null,
                  postfix: null,
                },
              },
              {
                size: 5,
                displayInList: true,
                position: 0,
                name: {
                  name: 'Alert 4 Config',
                  size: 1,
                  type: 'uint32_t',
                },
                value: {
                  size: 4,
                  dataFormat: 'Number',
                  type: 'uint32_t',
                  range: '0-255',
                  initialValue: 0,
                  properties: ['R', 'W'],
                  whenToUpdate: '',
                  remarks: '',
                  prefix: null,
                  postfix: null,
                },
              },
              {
                size: 5,
                displayInList: true,
                position: 0,
                name: {
                  name: 'Alert 7 Config',
                  size: 1,
                  type: 'uint32_t',
                },
                value: {
                  size: 4,
                  dataFormat: 'Number',
                  type: 'uint32_t',
                  range: '0-255',
                  initialValue: 0,
                  properties: ['R', 'W'],
                  whenToUpdate: '',
                  remarks: '',
                  prefix: null,
                  postfix: null,
                },
              },
              {
                size: 5,
                displayInList: true,
                position: 0,
                name: {
                  name: 'Alert 8 Config',
                  size: 1,
                  type: 'uint32_t',
                },
                value: {
                  size: 4,
                  dataFormat: 'Number',
                  type: 'uint32_t',
                  range: '0-255',
                  initialValue: 0,
                  properties: ['R', 'W'],
                  whenToUpdate: '',
                  remarks: '',
                  prefix: null,
                  postfix: null,
                },
              },
              {
                size: 5,
                displayInList: true,
                position: 0,
                name: {
                  name: 'Alert 11 Config',
                  size: 1,
                  type: 'uint32_t',
                },
                value: {
                  size: 4,
                  dataFormat: 'Number',
                  type: 'uint32_t',
                  range: '0-255',
                  initialValue: 0,
                  properties: ['R', 'W'],
                  whenToUpdate: '',
                  remarks: '',
                  prefix: null,
                  postfix: null,
                },
              },
              {
                size: 5,
                displayInList: true,
                position: 0,
                name: {
                  name: 'Alert 12 Config',
                  size: 1,
                  type: 'uint32_t',
                },
                value: {
                  size: 4,
                  dataFormat: 'Number',
                  type: 'uint32_t',
                  range: '0-255',
                  initialValue: 0,
                  properties: ['R', 'W'],
                  whenToUpdate: '',
                  remarks: '',
                  prefix: null,
                  postfix: null,
                },
              },
              {
                size: 5,
                displayInList: true,
                position: 0,
                name: {
                  name: 'Alert 150 Config',
                  size: 1,
                  type: 'uint32_t',
                },
                value: {
                  size: 4,
                  dataFormat: 'Number',
                  type: 'uint32_t',
                  range: '0-255',
                  initialValue: 0,
                  properties: ['R', 'W'],
                  whenToUpdate: '',
                  remarks: '',
                  prefix: null,
                  postfix: null,
                },
              },
              {
                size: 5,
                displayInList: true,
                position: 0,
                name: {
                  name: 'BLE Mode',
                  size: 1,
                  type: 'uint32_t',
                },
                value: {
                  size: 4,
                  dataFormat: 'Number',
                  type: 'uint32_t',
                  range: '0-1',
                  initialValue: 0,
                  properties: ['R', 'W'],
                  whenToUpdate: '',
                  remarks: '',
                  prefix: null,
                  postfix: null,
                },
              },
              {
                size: 5,
                displayInList: true,
                position: 0,
                name: {
                  name: 'BLE Tx Power',
                  size: 1,
                  type: 'uint32_t',
                },
                value: {
                  size: 4,
                  dataFormat: 'Number',
                  type: 'uint32_t',
                  range: '0-5',
                  initialValue: 0,
                  properties: ['R', 'W'],
                  whenToUpdate: '',
                  remarks: '',
                  prefix: null,
                  postfix: null,
                },
              },
              {
                size: 5,
                displayInList: true,
                position: 0,
                name: {
                  name: 'BLE Adv Frequency',
                  size: 1,
                  type: 'uint32_t',
                },
                value: {
                  size: 4,
                  dataFormat: 'Number',
                  type: 'uint32_t',
                  range: '0-65535',
                  initialValue: 0,
                  properties: ['R', 'W'],
                  whenToUpdate: '',
                  remarks: '',
                  prefix: null,
                  postfix: null,
                },
              },
            ],
          },
        ],
      },
      '8de47721-5496-4233-ae45-e4b306fe1182': {
        uuid: '8de47721-5496-4233-ae45-e4b306fe1181',
        name: 'Device Data STRING',
        size: '182 bytes',
        type: 'string',
        range: null,
        initialValue: null,
        properties: ['R'],
        sloanApp: '',
        remarks: '',
        generation: 'gen2',
        prefix: null,
        postfix: null,
        chunks: [
          {
            meta: [
              {
                name: '0x72',
                size: 1,
                position: 0,
                description:
                  'Byte Position 0: Start Flag, Ox72 signals the start of Integers write payload.',
              },
              {
                name: 'LEN',
                size: 1,
                position: 2,
                description:
                  'Byte Position 1: Integer value for the byte length of the package (includes all header bytes and End Flag).',
              },
              {
                name: '# of IDs',
                size: 1,
                position: 3,
                description:
                  'Byte Position 2: Integer value indicating how many Setting IDs to follow in Package.',
              },
              {
                name: '32',
                size: 1,
                position: 4,
                description:
                  'Byte Position 3: Integer value 32 indicates the Setting Value Size 32 = 32-bit size.',
              },
            ],
            uuidData: [
              {
                size: 5,
                displayInList: true,
                position: 0,
                name: {
                  name: 'AD Serial Number',
                  size: 1,
                  type: 'String',
                },
                value: {
                  size: 10,
                  dataFormat: 'ANNSSSSSSS',
                  type: 'String',
                  range: null,
                  initialValue: 'A000000000',
                  properties: ['R'],
                  whenToUpdate: 'At AD-BD connection',
                  remarks: '',
                  prefix: null,
                  postfix: null,
                },
              },
              {
                size: 5,
                displayInList: true,
                position: 0,
                name: {
                  name: 'BD Serial Number',
                  size: 1,
                  type: 'String',
                },
                value: {
                  size: 10,
                  dataFormat: 'ANNSSSSSSS',
                  type: 'String',
                  range: null,
                  initialValue: 'A000000000',
                  properties: ['R'],
                  whenToUpdate: 'At AD-BD connection',
                  remarks: '',
                  prefix: null,
                  postfix: null,
                },
              },
              {
                size: 5,
                displayInList: true,
                position: 0,
                name: {
                  name: 'AD Manufacturing Date',
                  size: 1,
                  type: 'String',
                },
                value: {
                  size: 6,
                  dataFormat: 'YYMMDD',
                  type: 'String',
                  range: null,
                  initialValue: '700101',
                  properties: ['R'],
                  whenToUpdate: 'At AD-BD connection',
                  remarks: '',
                  prefix: null,
                  postfix: null,
                },
              },
              {
                size: 5,
                displayInList: true,
                position: 0,
                name: {
                  name: 'BD Manufacturing Date',
                  size: 1,
                  type: 'String',
                },
                value: {
                  size: 6,
                  dataFormat: 'YYMMDD',
                  type: 'String',
                  range: null,
                  initialValue: '700101',
                  properties: ['R'],
                  whenToUpdate: 'At AD-BD connection',
                  remarks: '',
                  prefix: null,
                  postfix: null,
                },
              },
              {
                size: 5,
                displayInList: true,
                position: 0,
                name: {
                  name: 'AD Hardware Version',
                  size: 4,
                  type: 'String',
                },
                value: {
                  size: 4,
                  dataFormat: 'AAaa',
                  type: 'String',
                  range: null,
                  initialValue: '0000',
                  properties: ['R'],
                  whenToUpdate: 'At AD-BD connection',
                  remarks: '',
                  prefix: null,
                  postfix: null,
                },
              },
              {
                size: 5,
                displayInList: true,
                position: 0,
                name: {
                  name: 'AD Firmware Version',
                  size: 4,
                  type: 'String',
                },
                value: {
                  size: 4,
                  dataFormat: 'AAaa',
                  type: 'String',
                  range: null,
                  initialValue: '0000',
                  properties: ['R'],
                  whenToUpdate: 'At AD-BD connection',
                  remarks: '',
                  prefix: null,
                  postfix: null,
                },
              },
              {
                size: 5,
                displayInList: true,
                position: 0,
                name: {
                  name: 'BD Hardware Version',
                  size: 4,
                  type: 'String',
                },
                value: {
                  size: 4,
                  dataFormat: 'AAaa',
                  type: 'String',
                  range: null,
                  initialValue: 'assigned by Tester',
                  properties: ['R'],
                  whenToUpdate: 'At AD-BD connection',
                  remarks: '',
                  prefix: null,
                  postfix: null,
                },
              },
              {
                size: 5,
                displayInList: true,
                position: 0,
                name: {
                  name: 'BD Firmware Version',
                  size: 4,
                  type: 'String',
                },
                value: {
                  size: 4,
                  dataFormat: 'AAaa',
                  type: 'String',
                  range: null,
                  initialValue: 'BDFW hard-coded',
                  properties: ['R'],
                  whenToUpdate: 'At AD-BD connection',
                  remarks: '',
                  prefix: null,
                  postfix: null,
                },
              },
              {
                size: 5,
                displayInList: true,
                position: 0,
                name: {
                  name: 'Full Name',
                  size: 4,
                  type: 'String',
                },
                value: {
                  size: 30,
                  dataFormat: '30 characters',
                  type: 'String',
                  range: null,
                  initialValue: '',
                  properties: ['R', 'W'],
                  whenToUpdate: 'every Full Name change',
                  remarks: '',
                  prefix: null,
                  postfix: null,
                },
              },
              {
                size: 5,
                displayInList: true,
                position: 0,
                name: {
                  name: 'Nick Name',
                  size: 4,
                  type: 'String',
                },
                value: {
                  size: 6,
                  dataFormat: '6 characters',
                  type: 'String',
                  range: null,
                  initialValue: '',
                  properties: ['R', 'W'],
                  whenToUpdate: 'every Nickname change',
                  remarks: '',
                  prefix: null,
                  postfix: null,
                },
              },
              {
                size: 5,
                displayInList: true,
                position: 0,
                name: {
                  name: 'BD Note',
                  size: 4,
                  type: 'String',
                },
                value: {
                  size: 120,
                  dataFormat: '120 characters',
                  type: 'String',
                  range: null,
                  initialValue: '',
                  properties: ['R', 'W'],
                  whenToUpdate: 'every BD Note change',
                  remarks:
                    'BD Note 1 (40 bytes), BD Note 2 (40 bytes), BD Note 3 (40 bytes)',
                  prefix: null,
                  postfix: null,
                },
              },
            ],
          },
          {
            meta: [
              {
                name: '0x72',
                size: 1,
                position: 0,
                description:
                  'Byte Position 0: Start Flag, Ox72 signals the start of Integers write payload.',
              },
              {
                name: 'LEN',
                size: 1,
                position: 2,
                description:
                  'Byte Position 1: Integer value for the byte length of the package (includes all header bytes and End Flag).',
              },
              {
                name: '# of IDs',
                size: 1,
                position: 3,
                description:
                  'Byte Position 2: Integer value indicating how many Setting IDs to follow in Package.',
              },
              {
                name: '32',
                size: 1,
                position: 4,
                description:
                  'Byte Position 3: Integer value 32 indicates the Setting Value Size 32 = 32-bit size.',
              },
            ],
            uuidData: [
              {
                size: 5,
                displayInList: true,
                position: 0,
                name: {
                  name: 'Alert 0 Config',
                  size: 1,
                  type: 'uint32_t',
                },
                value: {
                  size: 4,
                  dataFormat: 'Number',
                  type: 'uint32_t',
                  range: '0-255',
                  initialValue: 0,
                  properties: ['R', 'W'],
                  whenToUpdate: '',
                  remarks: '',
                  prefix: null,
                  postfix: null,
                },
              },
            ],
          },
        ],
      },
    },
  },
};
