import {STYLE} from './STYLE';
export const EULA_HTML = {
  html: `${STYLE} 
       <body style="color: #666">
          <div class="eula" style="padding:30px">
              <h2>SLOAN VALVE COMPANY—ELECTRONIC PRODUCT AND PRODUCT APP END USER LICENSE AGREEMENT AND TERMS OF USE</h2>
              <h2>END USER LICENSE AGREEMENT</h2>
              <p>The Sloan Electronic Product software application (the <q><strong>Licensed Application</strong></q>?) that is the subject of this End User License Agreement (this <q><strong>License</strong></q>?), is hereby licensed, not sold, to you, the licensee (<q><strong>You</strong></q>?), by Sloan Valve Company, the licensor (<q><strong>Sloan</strong></q>?), strictly for use by You only under the terms of this License.  Sloan hereby reserves all rights not expressly granted to You in this License.</p>
              <p><strong>DO NOT USE THE LICENSED APPLICATION and/or the Sloan Electronic Product (the <q>Sloan Product</q>?), sold separately, unless and until You have carefully read the terms of this license, the Sloan Privacy Policy (located at
                  <a href="https://www.sloan.com/privacy-policy">https://www.sloan.com/privacy-policy</a>) and the Disclaimer of Liability set forth below (the <q>Disclaimer</q>?) and agree to bound by these provisions. Be sure to abide by all local, state and federal laws. It is Your responsibility to know what those laws are and how they apply to You. The installation and use of the Licensed Application (with or without the Sloan Product) indicates that You have (a) had the opportunity to inquire about applicable local, state and federal laws and (b) read and understand, and accept all of the terms of, this License (including the below Disclaimer) and the Sloan Privacy Policy.</strong></p>
              <p>The terms of this License are as follows:</p>
              <ol type="A">
                  <li>Scope of License: This License granted to You for the Licensed Application by Sloan is personal and limited to a non-exclusive, worldwide, perpetual and non-transferable license to perform, display and use the Licensed Application on any iPhone, iPod touch, iPad, Android smartphone, Android tablet or any other compatible mobile device that You own or control and as permitted by the applicable usage rules set forth in the Apple and Google terms and conditions (the <q><strong>Usage Rules</strong></q>?).  This license does not allow You to use the Licensed Application on any iPhone, iPod touch,  iPad, Android smartphone or Android tablet that You do not own or control, and You may not distribute or make the Licensed Application available over a network where it could be used by multiple devices at the same time.  You may not rent, lease, lend, sell, redistribute or sublicense the Licensed Application.  You may not copy (except as expressly permitted by this License and the Usage Rules), decompile, reverse engineer, disassemble, attempt to derive the source code of, modify, or create derivative works of the Licensed Application, any updates, or any part thereof (except as and only to the extent any foregoing restriction is prohibited by applicable law or to the extent as may be permitted by the licensing terms governing use of any open sourced components included with the Licensed Application, if any).  You may not use the Licensed Application to interface with any Sloan Product unless You have express permission to do so from the owner of such Sloan Product.  You may not use the Licensed Application with hardware other than the Sloan Product (which may be purchased separately from Sloan or an authorized Sloan reseller). All programming, performance tests, diagnostics, and data monitoring conducted using this Licensed Application must be performed in accordance with the rules and instructions of Sloan.  Any attempt to do any of the restricted activities described in this License is a violation of the rights of Sloan.  If You breach any of these restrictions, You may be subject to prosecution, damages and termination of this License (including access and use of the Licensed Application).  The terms of this License will govern any updates provided by Sloan that replace and/or supplement the original Licensed Application, unless such upgrade is accompanied by a separate license in which case the terms of that license will govern to the extent of any conflicts with the terms of this License.</li>
                  <li>Consent to Use of Data:  You hereby acknowledge and agree that Sloan may collect and use any and all information related to Your registration and use of the Licensed Application, including but not limited to technical information and data related to the Sloan Product, the use of the Licensed Application in connection with the Sloan Product, information periodically gathered from the Licensed Application to facilitate the provision of updates, Licensed Application support, Licensed Application functionality that You access and use, personal information that You provide, the unique device identifier (i.e., sequence of numbers or characters that are unique to the mobile device on which the Licensed Application is used), and other services accessed by or provided to You (if any) related to the Licensed Application.  You hereby acknowledge and agree that and consent to Sloan’s use of this information in accordance with the Sloan Privacy Policy to improve its Licensed Application and/or products or to provide services or technologies to You, and use of this information by way of disclosure to the owner of the applicable Sloan Products or any governmental authority in the event that You use the Licensed Application for any activity that is not authorized under this License, applicable law or contrary to any covenant, representation or warranty made by You under this License, or otherwise breach any obligation under this License.</li>
                  <li>Termination. This License is effective until terminated by You or Sloan.  Your rights under this License will terminate automatically without notice from Sloan if You fail to comply with any term(s) of this License, including, without limitation, use of the Licensed Application for unauthorized interface with or adjustment of any Sloan Product for which You do not have express permission to do so from the owner of such Sloan Product.  Upon termination of this License, You shall cease all use of the Licensed Application, and destroy or otherwise permanently delete all copies, full or partial, of the Licensed Application.</li>
                  <li>Services; Third Party Materials. The Licensed Application may enable access to services and web sites of Sloan and third parties (collectively and individually, <q><strong>Services</strong></q>?).  Use of the Services may require Internet access and You hereby accept any additional terms of service or other provisions in connection therewith. Additionally, You agree as follows:</li>
                  <ol type="a">
                      <li>You understand that by using any of the Services, You may encounter registered and/or unregistered marks owned by third parties.  You agree that You will not be confused by Sloan’s  display of such third party marks and that You will use the Services at Your sole risk and that Sloan shall not have any liability to You for any issues arising from the use of the Licensed Application or any Sloan Product programmed, monitored, gauged, tested, or diagnosed using the Licensed Application in conjunction with other equipment.</li>
                      <li>Certain Services may display, include or make available content, data, information, applications or materials from third parties (<q><strong>Third Party Materials</strong></q>?) or provide links to certain third party web sites.  By using the Services, You acknowledge and agree that Sloan is not responsible for examining or evaluating the content, accuracy, completeness, timeliness, validity, copyright compliance, legality, decency, quality or any other aspect of such Third Party Materials or web sites.  Sloan does not warrant or endorse and does not assume and will not have any liability or responsibility to You or any other person for any third-party Services, Third Party Materials or web sites, or for any other materials, licensed applications, products or services of third parties.  Third Party Materials and links to other web sites are provided solely as a convenience to You.</li>
                      <li> You agree that the Services may contain proprietary content, information and material that is protected by applicable intellectual property and other laws, including but not limited to laws governing copyrights, trademarks, trade secrets, and patents, and that You will not use such proprietary content, information or materials in any way whatsoever except for permitted use of the Services.  No portion of the Services may be reproduced in any form or by any means.  You agree not to modify, rent, lease, loan, sell, distribute, or create derivative works based on the Services, in any manner, and You shall not exploit the Services in any unauthorized way whatsoever, including but not limited to, by trespass or burdening network capacity.</li>
                      <li>In addition, third party Services and Third Party Materials that may be accessed from, displayed on or linked to from Your iPhone, iPod touch, iPad, Android smartphone or Android tablet are not available in all languages or in all countries.  Sloan makes no representation that such Services and Third Party Materials are appropriate or available for use in any particular location.  To the extent You choose to access such Services or Third Party Materials, You do so at Your own initiative and are responsible for compliance with any applicable laws, including but not limited to applicable local laws.  Sloan reserves the right to change, suspend, remove, or disable access to any Services at any time without notice.  In no event will Sloan be liable for the removal of or disabling of access to any such Services.  Sloan may also impose limits on the use of or access to certain Services, in any case and without notice or liability.</li>
                  </ol>
                  <li>NO WARRANTY: YOU EXPRESSLY ACKNOWLEDGE AND AGREE THAT, TO THE MAXIMUM EXTENT PERMITTED BY APPLICABLE LAW, USE OF THE LICENSED APPLICATION IS AT YOUR SOLE RISK AND THAT THE ENTIRE RISK AS TO SATISFACTORY QUALITY, PERFORMANCE, ACCURACY AND EFFORT IS WITH YOU.  TO THE MAXIMUM EXTENT PERMITTED BY APPLICABLE LAW, THE LICENSED APPLICATION AND ANY SERVICES PERFORMED OR PROVIDED BY THE LICENSED APPLICATION (<q><strong>LICENSED APPLICATION SERVICES</strong></q>?) ARE PROVIDED <q>AS IS</q>? AND <q>AS AVAILABLE</q>?, WITH ALL FAULTS AND WITHOUT WARRANTY OF ANY KIND, AND SLOAN HEREBY DISCLAIMS ALL WARRANTIES AND CONDITIONS WITH RESPECT TO THE LICENSED APPLICATION AND ANY LICENSED APPLICATION SERVICES, EITHER EXPRESS, IMPLIED OR STATUTORY, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED WARRANTIES AND/OR CONDITIONS OF MERCHANTABILITY, OF SATISFACTORY QUALITY, OF FITNESS FOR A PARTICULAR PURPOSE, OF ACCURACY, OF QUIET ENJOYMENT, TITLE AND NON-INFRINGEMENT OF THIRD PARTY RIGHTS.  SLOAN DOES NOT WARRANT AGAINST INTERFERENCE WITH YOUR ENJOYMENT OF THE LICENSED APPLICATION, THAT THE FUNCTIONS CONTAINED IN, OR LICENSED APPLICATION SERVICES PERFORMED OR PROVIDED BY, THE LICENSED APPLICATION WILL MEET YOUR REQUIREMENTS, THAT THE OPERATION OF THE LICENSED APPLICATION OR LICENSED APPLICATION SERVICES WILL BE UNINTERRUPTED OR ERROR-FREE, OR THAT DEFECTS IN THE LICENSED APPLICATION OR LICENSED APPLICATION SERVICES WILL BE CORRECTED.  NO ORAL OR WRITTEN INFORMATION OR ADVICE GIVEN BY SLOAN OR ITS AUTHORIZED REPRESENTATIVE SHALL CREATE A WARRANTY.  SHOULD THE LICENSED APPLICATION OR LICENSED APPLICATION SERVICES PROVE DEFECTIVE, YOU ASSUME THE ENTIRE COST OF ALL NECESSARY SERVICING, REPAIR OR CORRECTION.  SOME JURISDICTIONS DO NOT ALLOW THE EXCLUSION OF IMPLIED WARRANTIES OR LIMITATIONS ON APPLICABLE STATUTORY RIGHTS OF A CONSUMER, SO THE ABOVE EXCLUSION AND LIMITATIONS MAY NOT APPLY TO YOU.</li>
                  <li>Export; Re-Export; Prohibited Uses. You may not use or otherwise export or re-export the Licensed Application except as authorized by United States law and the laws of the jurisdiction in which the Licensed Application was obtained.  In particular, but without limitation, the Licensed Application may not be exported or re-exported (a) into any U.S. embargoed countries or (b) to anyone on the U.S. Treasury Department’s list of Specially Designated Nationals or the U.S. Department of Commerce Denied Person’s List or Entity List.  By using the Licensed Application, You represent and warrant that You are not located in any such country or on any such list.  You represent and warrant that (i) You are not located in a country that is subject to a U.S. Government embargo, or that has been designated by the U.S. Government as a <q>terrorist supporting</q>? country and (ii) You are not listed on any U.S. Government list of prohibited or restricted parties. You also agree that You will not use these Licensed Applications for any purposes prohibited by United States law, including, without limitation, the development, design, manufacture or production of nuclear, missiles, or chemical or biological weapons.</li>
                  <li>Commercial Items. The Licensed Application and related documentation are <q>Commercial Items</q>?, as that term is defined at 48 C.F.R. §2.101, consisting of <q>Commercial Computer Software</q>? and <q>Commercial Computer Software Documentation</q>?, as such terms are used in 48 C.F.R. §12.212 or 48 C.F.R. §227.7202, as applicable.  Consistent with 48 C.F.R. §12.212 or 48 C.F.R. §227.7202-1 through 227.7202-4, as applicable, the Commercial Computer Software and Commercial Computer Software Documentation are being licensed to U.S. Government end users (a) only as Commercial Items and (b) with only those rights as are granted to all other end users pursuant to the terms and conditions herein. Unpublished-rights reserved under the copyright laws of the United States.</li>
                  <li>Acknowledgements. The parties hereby acknowledge that: (a) Apple and Google have no obligation whatsoever to furnish any maintenance and/or support services with respect to the Licensed Application; (b) in the event of any failure of the Licensed Application to conform to an applicable warranty (if any), You may notify Apple or Google as applicable, and Apple or Google as applicable will refund the purchase price (if any) for the Licensed Application to You; and that, to the maximum extent permitted by applicable law, Apple and Google will have no other warranty obligation whatsoever with respect to the Licensed Application, and any other claims, losses, liabilities, damages, costs or expenses attributable to any failure to conform to any warranty will be Sloan’s sole responsibility; (c) Sloan, not Apple or Google, is responsible for addressing any claims by You or any third party relating to the Licensed Application or Your possession and/or use of the Licensed Application, including but not limited to (i) product liability claims, (ii) any claim that the Licensed Application fails to conform to any applicable legal or regulatory requirement and (iii) claims arising under consumer protection or similar legislation; (d) in the event of any third party claim that the Licensed Application or Your possession and use of that Licensed Application infringes that third party’s intellectual property rights, Sloan, not Apple or Google, will be solely responsible for the investigation, defense, settlement and discharge of any such intellectual property infringement claim; and (e) Apple and Google, and Apple’s and Google’s subsidiaries, are third party beneficiaries of this License and that, upon Your acceptance of the terms and conditions of this license, Apple and Google will have the right (and will be deemed to have accepted the right) to enforce this License against You as a third party beneficiary hereof.</li>
                  <ol type="a">
                      <li>The internal laws of the State of Illinois, excluding its conflicts of law rules, govern this license and your use of the Licensed Application.  Your use of the Licensed Application may also be subject to other local, state, national, or international laws.</li>
                  </ol>
              </ol>
              <p>Sloan Electronic Faucet - DISCLAIMER OF LIABILITY The Licensed Application is used to monitor, manage and control the Sloan Product which is produced and sold separately by Sloan. By electing to install and use the Licensed Application, You hereby agree to all of the following terms, conditions, waivers and disclaimers:</p>
              <ul>
                  <li>THE SLOAN PRODUCT USED WITH THE LICENSED APPLICATION CONTROLS THE FLOW OF WATER WHICH, IF NOT PROPERLY PROGRAMMED OR MONITORED, COULD CAUSE OVERFLOWS AND FLOODING WHICH COULD RESULT IN PERSONAL INJURY, PROPERTY DAMAGE AND OTHER ADVERSE CONDITIONS, EVENTS AND CONSEQUENCES, SOME OF WHICH MAY BE DIFFICULT TO FORESEE. USE THE APPLICATION AT YOUR OWN RISK AND ONLY WITH THE EXPRESS PERMISSION OF THE OWNER OF THE APPLICABLE SLOAN PRODUCT(S). Do not use the Licensed Application and/or Sloan Product unless and until You have carefully read this Disclaimer. The installation and use of the Licensed Application and/or Sloan Product indicates that You have read and understand, and accept all of the following terms of, this Disclaimer:</li>
                  <li>Sloan shall not be responsible for the proper installation, use and service of the Sloan Product and/or any peripheral equipment, devices or fixtures.  You assume full responsibility for the proper installation and application of the Sloan Product (including any peripheral equipment, devices and/or fixtures).  You shall look solely to the installer who installed the Sloan Product with respect to any responsibility for the installation or application of the Sloan Product, and any peripheral equipment, devices, fixtures, service and support needed by You with respect thereto, as well as any damage that may be done to the premises as a result of the installation of the Sloan Product(s), including any modifications made by the installer.</li>
                  <li>You are responsible to fully understand the capabilities and limitations of the Sloan Product, the Licensed Application, and use of the Licensed Application in connection with the Sloan Product, and agree to hold Sloan harmless from any damage or injury resulting from failure to adhere to any applicable manufacturer recommendations, warnings, instructions and manuals, including Your decision to change any manufacturer settings on the Sloan Products or use the Licensed Application in connection with any activity by You that is not expressly authorized by the owner of the Sloan Products. You are also responsible to obey all applicable federal, state, and local laws, statutes, and ordinances when using the Sloan Product, and You agree to hold Sloan harmless from any violation thereof.</li>
                  <li>Sloan’s Limited Warranty for the Sloan Product (found at <a href="https://www.sloan.com/resources/product-resources/warranty-information">https://www.sloan.com/resources/product-resources/warranty-information</a>) is the owner’s exclusive warranty and is in lieu of all other warranties, express or implied, except as may be required by applicable law. Without limiting the generality of the foregoing, Sloan shall not be liable for any breach of any other written or oral warranties that may be given by You or by any third party(ies) such as dealers or distributors of Sloan Products.</li>
                  <li>Consult the applicable premises insurance policy before using this Licensed Application in connection with any Sloan Product.  Under no circumstances will Sloan be liable for the voidance of applicable premises or other liability insurance coverage. Rather, You assume all risk and responsibility if an insurance provider voids any applicable insurance policy due to any use of this Licensed Application and the Sloan Product.</li>
                  <li>You will operate the Licensed Application and program only for use with those Sloan Products for which You have received prior authorization from the owner of such Sloan Product. Your use of the Licensed Application at all times will be strictly in accordance with Sloan’s operator’s manual and other manufacturer guidelines and instructions, and any similar instruction from the owner of such Sloan Products.  Regardless of any capability, feature or function of the Licensed Application or Sloan Product, You understand and acknowledge that it is Your sole responsibility to ensure that the applicable Sloan Products are programmed and operated in a safe and legal manner.  In no case will Sloan be held liable, and You assume all risk and responsibility, for any property damage, personal injury and/or death that may occur in the event that You operate the Licensed Application or program any Sloan Products in a manner contrary to Your obligations set forth herein or that results in overflows and/or flooding (or which otherwise violates any applicable law).</li>
                  <li>You acknowledge that You are not relying on Sloan’s skill or judgment to select or furnish goods suitable for any particular purpose, and You hereby waive all remedies or liabilities, expressed or implied, arising by law or otherwise, or whether or not occasioned by Sloan’s negligence.</li>
                  <li>TO THE EXTENT NOT PROHIBITED BY LAW, IN NO EVENT SHALL SLOAN BE LIABLE FOR PROPERTY DAMAGE, PERSONAL INJURY OR DEATH, OR ANY INCIDENTAL, SPECIAL, INDIRECT OR CONSEQUENTIAL DAMAGES WHATSOEVER, INCLUDING, WITHOUT LIMITATION, DAMAGES FOR LOSS OF PROFITS, LOSS OF DATA, BUSINESS INTERRUPTION OR ANY OTHER COMMERCIAL DAMAGES OR LOSSES, ARISING OUT OF OR RELATED TO YOUR USE OF OR INABILITY TO USE THE LICENSED APPLICATION, HOWEVER CAUSED, REGARDLESS OF THE THEORY OF LIABILITY (CONTRACT, TORT OR OTHERWISE) AND EVEN IF SLOAN HAS BEEN ADVISED OF THE POSSIBILITY OF SUCH DAMAGES.  In no event shall Sloan’s total liability to You for all damages (other than as may be required by applicable law in cases involving personal injury) exceed the amount of fifty dollars ($50.00).  The foregoing limitations will apply even if the above stated remedy fails of its essential purpose. Some jurisdictions do not allow the limitation of liability for personal injury, so this limitation may not apply to You.</li>
                  <li>The Licensed Application and the related Sloan Products are generally intended for use in commercial (not consumer) applications.  Nevertheless, to the extent the Licensed Application and/or any Sloan Product is determined to be subject to consumer protections, the following will apply:  (a)  Sloan’s Limited Warranty for the Sloan Product gives the owner of the Sloan Product specific legal rights, and such owner may also have other rights which may vary from state to state; (b) pertinent state law shall control for what period of time following the transaction a consumer may seek a remedy under the implied warranty of merchantability or fitness for a particular purpose; and (c) some states do not allow the exclusion or limitation of incidental or consequential damages so the above limitations or exclusions may not apply to You.</li>
                  <li>THIS DISCLAIMER IS A MATERIAL CONDITION OF SLOAN’S WILLINGNESS TO LICENSE THE LICENSED APPLICATION TO YOU. IN THE EVENT THAT YOU DO NOT AGREE WITH THIS DISCLAIMER, YOU SHOULD IMMEDIATELY AND PERMANENTLY DISCONTINUE YOUR USE OF THE LICENSED APPLICATION.</li>
                  <li>If You have questions, complaints or concerns, they should be directed to Sloan Valve Company (a) by mail at 10500 Seymour Avenue, Franklin Park, Illinois 60131 Attention: Customer Service attn.: Sloan Connect App (b) by telephone at <a href="tel:+18476714300">+1-847-671-4300</a> or (c) by e-mail at
                      <a href="mailto:customer.service@sloan.com?subject=Sloan%20Connect%20App">customer.service@sloan.com</a>.</li>
              </ul>
          </div>
          <div class="terms" style="padding:30px">
              <h2>SLOAN VALVE COMPANY—ELECTRONIC PRODUCT TERMS OF USE</h2>
              <p>By using the software, firmware, middleware or any other computer code (<q><strong>Product Software</strong></q>?) that is embedded on the Sloan product (<q><strong>Product</strong></q>?), You, the licensee (<q>You</q>?) agree to these terms of use (<q>Terms of Use</q>?) between You and Sloan Valve Company (<q><strong>Sloan</strong></q>? or <q><strong>we</strong></q>?). IF YOU DO NOT AGREE TO THESE TERMS OF USE, YOU MAY NOT USE THE PRODUCT SOFTWARE AND YOU MAY CHOOSE TO PROMPTLY RETURN THE PRODUCT FOR A REFUND OF THE PRODUCT PURCHASE PRICE BY CONTACTING SLOAN AT THE ADDRESS BELOW.</p>
              <p>These Terms of Use govern Your access and use of the Product Software. These Terms of Use give You specific legal rights, and You may also have other legal rights in addition, which vary from jurisdiction to jurisdiction. The disclaimers, exclusions, and limitations of liability under these Terms of Use will not apply to the extent prohibited by applicable law. Some jurisdictions do not allow the exclusion of implied warranties or the exclusion or limitation of incidental or consequential damages or other rights under certain circumstances, so those provisions of these Terms of Use may not apply to You.</p>
              <p>THIS IS A LEGAL AGREEMENT. BY ACCESSING AND USING THE PRODUCT SOFTWARE, YOU ACCEPT AND AGREE TO THESE TERMS OF USE ON BEHALF OF YOURSELF OR THE ENTITY YOU REPRESENT IN CONNECTION WITH SUCH ACCESS AND/OR USE. YOU REPRESENT AND WARRANT THAT YOU HAVE THE RIGHT, AUTHORITY, AND CAPACITY TO ACCEPT AND AGREE TO THESE TERMS OF USE ON BEHALF OF YOURSELF OR THE ENTITY YOU REPRESENT. YOU REPRESENT THAT YOU ARE OF SUFFICIENT LEGAL AGE IN YOUR JURISDICTION OR RESIDENCE TO USE OR ACCESS THE PRODUCT SOFTWARE AND TO ENTER INTO THESE TERMS OF USE. IF YOU DO NOT AGREE WITH ANY OF THE PROVISIONS OF THESE TERMS, YOU SHOULD CEASE ACCESSING OR USING THE PRODUCT SOFTWARE.</p>
              <p>AS DESCRIBED HEREIN, YOU HEREBY CONSENT TO AUTOMATIC SOFTWARE UPDATES OF THE PRODUCT SOFTWARE AND THE COLLECTION AND USE OF PRODUCT INFORMATION (AS DEFINED HEREIN) REGARDING THE USE AND OPERATION OF THE PRODUCT AND THE PRODUCT SOFTWARE AND PERSONAL INFORMATION. IF YOU DO NOT AGREE, YOU MUST NOT USE THE PRODUCT OR THE PRODUCT SOFTWARE.</p>
              <p>AS DESCRIBED HEREIN, SECTION 10 DESCRIBES IMPORTANT LIMITATIONS OF THE PRODUCT SOFTWARE AND RELATED SERVICES, ESPECIALLY IN CONNECTION WITH LIFE, SAFETY AND CRITICAL USES. PLEASE READ THESE DISCLOSURES CAREFULLY, AS YOU HEREBY ACKNOWLEDGE AND ACCEPT THESE LIMITATIONS.</p>
              <ol type="1">
                  <li>License.</li>
                  <p>Subject to these Terms of Use, Sloan grants to You a limited, personal and nonexclusive license (without the right to sublicense) to execute one (1) copy of the Product Software, in executable object code form only, solely on the Product that You own or control and solely for use in conjunction with the intended purpose of the Product.</p>
                  <li>Restrictions.</li>
                  <p>You will not, and You will not permit others to, (a) license, sell, rent, lease, assign, distribute, transmit, host, outsource, disclose or otherwise commercially exploit the Product Software or make the Product Software available to any third party, (b) copy or use the Product Software for any purpose other than as permitted in Section 1, (c) use any portion of the Product Software on any device or computer other than the Product that You own or control, (d) remove or alter any trademark, logo, copyright or other proprietary notices, legends, symbols or labels in the Product Software, or (e) modify, make derivative works of, disassemble, reverse compile or reverse engineer any part of the Product Software (except to the extent applicable laws specifically prohibit such restriction for interoperability purposes, in which case You will first contact Sloan and provide Sloan an opportunity to create such changes as are needed for interoperability purposes). You may not release the results of any performance or functional evaluation of any of the Product Software to any third party without prior written approval of Sloan for each such release.</p>
                  <li>Automatic Software Updates.</li>
                  <p>Sloan may from time to time develop patches, bug fixes, updates, upgrades and other modifications to improve the performance of the Product Software and related services (<q><strong>Updates</strong></q>?).  These may be automatically installed without providing any additional notice or receiving any additional consent.  You consent to this automatic update.  If You do not want such Updates, Your remedy is to stop using the Product. If You do not cease using the Product, You may receive Updates automatically.  Alternatively, in Sloan’s sole discretion, Sloan may instead send You Updates to be installed.  You acknowledge that You may be required to install Updates to use the Product and the Product Software and You will promptly install any Updates Sloan provides. Your continued use of the Product is Your consent and agreement to these Terms of Use.</p>
                  <li>Product Information</li>
                  <ol type="a">
                      <li>
                          The Product Software may collect, use, share and store information related the use and operation of the Products in Your premises and their connection with other products and services, such as, for example only, web apps, mobile apps, etc., and such information may include personal information (i.e., information that personally identifies You, such as Your name, email address or billing information, or other data that can be reasonably used to infer this information) (<q><strong>Product Information</strong></q>?). All Product Information is provided <q>as is</q>? and <q>as available</q>?. We cannot guarantee that it is correct or up to date. In cases where it is critical, accessing Product Information through the Product Software is not a substitute for direct access of the information in the premises.
                      </li>
                      <li>
                          By using Product, You consent agree to allow Sloan to collect and process Product Information as described herein and the Sloan Privacy Policy (located at
                          <a href="https://www.sloan.com/privacy-policy">https://www.sloan.com/privacy-policy</a>).  The Product Information may be collected, processed and stored by Sloan or its service providers in the United States and other countries where our servers reside. Please be aware that the privacy protections and legal requirements, including the rights of authorities to access Your personal information, in some of these countries may not be equivalent to those in Your country. If You are using Sloan Products in the European Economic Area or other regions with laws governing data collection and use that may differ from United States law, You consent to the transfer of Your personal data to the United States and other countries where Sloan operates. Additional information is provided herein as to how Sloan protects Your Product Information when it is transferred internationally.
                      </li>
                      <li>
                          The Product may collect the following Product Information:
                          <ol type="i">
                              <li>
                                  Setup information You provide: When You install the Product, You’ll be asked several questions in order to create an initial program of settings. For example, we’ll ask for Your name, phone number and email, the name of the company that you work for, your title at the company, and the country in which you reside and the company is based. This information enables us to communicate with You during the registration and activation process of the Product.
                              </li>
                              <li>
                                  Direct adjustments to the Product: If You change settings on the Product, it records and feeds that information to the Product algorithms to learn Your desired settings.
                              </li>
                              <li>
                                  Water usage information: Every time Your system turns on and off, the Product records the time and duration during which Your system was on in order to offer You features such as usage history.
                              </li>
                              <li>
                                  Technical information from the Product: In order to improve Your experience over time and help troubleshoot any problem You may encounter with the Product, we record Your Product model and serial number, software version, and technical information such as battery charge level and battery change frequency.
                              </li>
                              <li>
                                  Location of Product.
                              </li>
                              <li>
                                  Additional information as additional capabilities are developed and disclosed to You from time to time.
                              </li>
                          </ol>
                      </li>
                      <li>
                          If You have multiple Products interfacing with one another, the Products will share certain information with each other. This sharing may occur locally among connected Products. Sharing can also occur between Products and the mobile device or application that You or Your designated agents use to service and maintain the Products, or among Sloan’s servers.
                      </li>
                      <li>
                          To connect the Product to Sloan services or to access the Product over the Internet or a web or mobile app from a computer, a smartphone or a tablet, You will need to activate and/or connect it to communication functionality, such as, for example only, Wi-Fi network, Bluetooth or the like. During setup, the Product will initiate a <q>hand shake</q>? protocol to connect the Product to the Internet, smartphone, tablet, etc. It will save this information on the device, including any IP address, unique device identifier, phone number and other identifying information for the smartphone, tablet, etc., so that You can access it and control it from Your computer, smartphone or tablet, and so that it can communicate with Sloan servers and download software updates. Once connected, the Product regularly sends the data described herein (and the Sloan Privacy Policy) to Sloan to provide You with the services and Product Information.
                      </li>
                      <li>
                          During the registration and activation process, we collect and store Your email address and smartphone number. From that point forward, Your email address and mobile phone number are used for communications from Sloan.
                      </li>
                      <li>
                          You may choose to enable certain features or device pairing. If You do this, You’ll be asked to share location data from Your mobile device or from additional authorized users. This data may be processed or combined with data from other products to enhance certain features.
                      </li>
                      <li>
                          Bluetooth-enabled Products may broadcast an identifying signal wirelessly. This is used to connect with Your Bluetooth-enabled devices (such as a smartphone or tablet) in order to deliver features like easy setup or app silence.
                      </li>
                      <li>
                          Remember that when You visit Sloan websites, Sloan collects personal information as described in the Sloan Privacy Policy. Like most Internet sites, we routinely record log entries (including information such as Your IP address) and technical information (such as Your browser type and version) when Your browser, mobile device or Product contacts our servers.
                      </li>
                      <li>
                          We use this information to provide, develop and improve Products and services, including to make assessments and recommendations about products, safety, or water use. We may use Your contact details to send You this information, or to ask You to participate in surveys about Your Sloan use, and to send You other communications from Sloan. We may also use this information in an aggregated, non-identified form for research purposes and to help us make sales, marketing, and business decisions. We may use service providers to perform some of these functions. Those service providers are restricted from sharing Your information for any other purpose. We use generally accepted approved industry-standard methods to keep this information safe and secure while it is transmitted over Your network and through the Internet to our servers. Depending on Your location and type of data, Sloan may process Your personal information on servers that are not in Your home country.
                      </li>
                      <li>
                          Under no circumstance do we share Your personal information for any commercial or marketing purpose unrelated to Sloan products and services without asking You first.  We do not rent or sell our customer lists.  The following are the limited situations where we may share personal information:
                          <ol type="i">
                              <li>
                                  With Your consent.
                              </li>
                              <li>
                                  For external processing: We have vendors, service providers, and technicians who help with some of our processing and storage, including helping to answer Your questions. They may also assist with monitoring our servers for technical problems.  These technicians (as well as Sloan employees) can access certain information about You or Your account in line with this work but these technicians are not allowed to use this data for non-Sloan purposes.
                              </li>
                              <li>
                                  As part of business transitions: Upon the sale or transfer of the company and/or all or part of its assets, Your personal information may be among the items sold or transferred. We will request a purchaser to treat our data under the privacy statement in place at the time of its collection.
                              </li>
                              <li>
                                  For legal reasons: We may provide information to a third party if we believe in good faith that we are required to do so for legal reasons. For example, we may disclose information in response to legal process and we may disclose information in response to lawful requests by public authorities in the United States and other countries for the purposes of law enforcement and national security.
                              </li>
                          </ol>
                      </li>
                      <li>
                          When You select an outside party for the purchase, installation, or service of Your Sloan device and share Your personal information, we cannot control the collection, storage or sharing of information collected by that party. For example, when You buy a Product from an authorized retailer, the authorized retailer may collect personal information as part of the transaction. Or the party that installed the device may retain information that You provided to them to assist them in servicing the device if needed. Always check the privacy policies for any company that collects Your personal information.
                      </li>
                      <li>
                          Sloan generally stores Your personal information on Sloan’s servers until You delete or edit it, or for as long as You remain a Sloan customer in order to provide You with Products. As described above, some information is processed and stored directly on the Product. All personal information is encrypted as it is transmitted to Sloan and cannot easily be accessed. You can delete the information on the Product by resetting it to the defaults. Because of the way we maintain certain services, after Your information is deleted, backup copies may linger for some time before they are deleted, and we may retain certain data for a longer period of time if we are required to do so for legal reasons.
                      </li>
                  </ol>
                  <li>Ownership.</li>
                  <p>The Product Software and all worldwide copyrights, trade secrets, and other intellectual property rights therein are the exclusive property of Sloan. Sloan reserves all rights in and to the Product Software not expressly granted to You in these Terms of Use. The Product Software (and all copies thereof) is licensed to You, not sold, under these Terms of Use. There are no implied licenses in these Terms of Use. All suggestions or feedback provided by You to Sloan with respect to the Product Software shall be Sloan’s property. Sloan may use, copy, modify, publish, or redistribute the submission and its contents for any purpose and in any way without any compensation to You. You also agree that Sloan does not waive any rights to use similar or related ideas previously known to Sloan, developed by its employees, or obtained from other sources.</p>
                  <li>Open Source.</li>
                  <p>Certain items of software included with the Product Software may be subject to <q>open source</q>? or <q>free software</q>? licenses (<q><strong>Open Source Software</strong></q>?). Some of the Open Source Software is owned by third parties. The Open Source Software is not subject to the terms and conditions of these Terms of Use. Instead, each item of Open Source Software is licensed under the terms of the end user license that accompanies such Open Source Software. Nothing in these Terms of Use limits Your rights under, or grants You rights that supersede, the terms and conditions of any applicable end user license for the Open Source Software. If required by any license for particular Open Source Software, Sloan makes such Open Source Software, and Sloan’s modifications to that Open Source Software, available by written request to Sloan at the email or mailing address listed below.</p>
                  <li>Term and Termination.</li>
                  <p>These Terms of Use and the license granted hereunder are effective on the date You first use the Product Software or Product and shall continue for as long as You own the Product, unless these Terms of Use are terminated under this section. Sloan may terminate these Terms of Use at any time if You fail to comply with any term(s) hereof. You may terminate these Terms of Use effective immediately upon written email notice to Sloan at
                      <a href="mailto:customer.service@sloan.com?subject=Sloan%20Connect%20App%20terms%20of%20use">customer.service@sloan.com</a>, ATTN: Sloan Connect App. Upon termination of these Terms of Use, the license granted hereunder will terminate and You must stop all use of the Product Software, but the terms of Sections 2 through 19 (inclusive) will remain in effect, after any such termination.</p>
                  <li>Warranty Disclaimer.</li>
                  <p>NOTWITHSTANDING ANYTHING TO THE CONTRARY AND TO THE MAXIMUM EXTENT PERMITTED BY APPLICABLE LAW, SLOAN PROVIDES THE PRODUCT SOFTWARE <q>AS-IS</q>? AND DISCLAIMS ALL WARRANTIES AND CONDITIONS, WHETHER EXPRESS, IMPLIED, OR STATUTORY, INCLUDING THE WARRANTIES OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE, TITLE, QUIET ENJOYMENT, ACCURACY, AND NON-INFRINGEMENT OF THIRD-PARTY RIGHTS. SLOAN DOES NOT GUARANTEE ANY SPECIFIC RESULTS FROM THE USE OF THE PRODUCT SOFTWARE. SLOAN MAKES NO WARRANTY THAT THE PRODUCT SOFTWARE WILL BE UNINTERRUPTED, FREE OF VIRUSES OR OTHER HARMFUL CODE, TIMELY, SECURE, OR ERROR-FREE.</p>
                  <p>YOU USE ALL PRODUCT INFORMATION (AS DEFINED HEREIN), THE PRODUCT SOFTWARE, AND THE PRODUCT AT YOUR OWN DISCRETION AND RISK. YOU WILL BE SOLELY RESPONSIBLE FOR (AND SLOAN DISCLAIMS) ANY AND ALL LOSS, LIABILITY, OR DAMAGES, TO YOUR PLUMBING, PREMISES, PRODUCT, OTHER PERIPHERALS CONNECTED TO THE PRODUCT, AND ALL OTHER ITEMS IN YOUR PREMISES, RESULTING FROM YOUR USE OF THE PRODUCT INFORMATION, PRODUCT SOFTWARE, OR PRODUCT.</p>
                  <li>Limitation of Liability</li>
                  <p>Nothing in these Terms of Use and in particular within this "Limitation of Liability" clause shall attempt to exclude liability that cannot be excluded under applicable law.</p>
                  <p>TO THE MAXIMUM EXTENT PERMITTED BY APPLICABLE LAW, IN ADDITION TO THE ABOVE WARRANTY DISCLAIMERS, IN NO EVENT WILL (A) SLOAN BE LIABLE FOR ANY CONSEQUENTIAL, EXEMPLARY, SPECIAL, OR INCIDENTAL DAMAGES, INCLUDING ANY DAMAGES FOR LOST DATA OR LOST PROFITS, ARISING FROM OR RELATING TO THE PRODUCTS OR PRODUCT SOFTWARE, EVEN IF SLOAN KNEW OR SHOULD HAVE KNOWN OF THE POSSIBILITY OF SUCH DAMAGES, AND (B) SLOAN’S’ TOTAL CUMULATIVE LIABILITY ARISING FROM OR RELATED TO THE PRODUCTS AND PRODUCT SOFTWARE, WHETHER IN CONTRACT OR TORT OR OTHERWISE, EXCEED THE PRICE ACTUALLY PAID BY YOU TO SLOAN OR SLOAN’S AUTHORIZED RESELLER FOR THE PRODUCT AT ISSUE IN THE PRIOR 12 MONTHS (IF ANY). THIS LIMITATION IS CUMULATIVE AND WILL NOT BE INCREASED BY THE EXISTENCE OF MORE THAN ONE INCIDENT OR CLAIM. SLOAN DISCLAIMS ALL LIABILITY OF ANY KIND OF SLOAN’S SUPPLIERS.</p>
                  <li>Limitations of Product Software</li>
                  <p>You acknowledge that the Products and Product Software are not certified for emergency response. YOU UNDERSTAND THAT THE PRODUCTS AND PRODUCT SOFTWARE ARE NOT A THIRD-PARTY MONITORED EMERGENCY NOTIFICATION SYSTEM -- SLOAN DOES NOT MONITOR EMERGENCY NOTIFICATIONS AND WILL NOT DISPATCH EMERGENCY AUTHORITIES TO YOUR PREMISES IN THE EVENT OF AN EMERGENCY. In addition, the Sloan Customer Care and Support contacts cannot be considered a lifesaving solution for people at risk in the premises, and they are no substitute for emergency services. All life threatening and emergency events should be directed to the appropriate response services.</p>
                  <p>Unless explicitly promising a <q>guarantee,</q>? Sloan does not guarantee or promise any specific level of water savings or other monetary benefit from the use of the Products or Product Software or any feature of them. Actual water savings and monetary benefits vary with factors beyond Sloan’s control or knowledge. From time to time, Sloan may use the Product Software to provide You with information that is unique to You and Your water usage and suggests an opportunity to save money on water bills if You adopt suggestions or features of the Product or Product Software. We do this to highlight an opportunity based on our analysis and information about You and Your business. You acknowledge that these promotions are not a guarantee of actual savings, and You agree not to seek monetary or other remedies from Sloan if Your savings differ.</p>
                  <li>Confidentiality</li>
                  <p><q>Confidential Information</q>? shall mean the Product Software and all other information disclosed to You that Sloan characterizes as confidential at the time of its disclosure either in writing or orally, except for information which You can demonstrate: (a) is previously rightfully known to You without restriction on disclosure; (b) is or becomes, from no act or failure to act on Your part, generally known in the relevant industry or public domain; (c) is disclosed to You by a third party as a matter of right and without restriction on disclosure; or (d) is independently developed by You without access to the Confidential Information. You shall use Your best efforts to preserve and protect the confidentiality of the Confidential Information at all times, both during the term hereof and for a period of at least three (3) years after termination of these Terms of Use, provided, however, that any source code You receive shall be held in confidence in perpetuity. You shall not disclose, disseminate or otherwise publish or communicate Confidential Information to any person, firm, corporation or other third party without the prior written consent of Sloan. You shall not use any Confidential Information other than in the course of the activities permitted hereunder. You shall notify Sloan in writing immediately upon discovery of any unauthorized use or disclosure of Confidential Information or any other breach of these Terms of Use, and will cooperate with Sloan in every reasonable way to regain possession of Confidential Information and prevent any further unauthorized use. If You are legally compelled to disclose any of the Confidential Information, then, prior to such disclosure, You will (i) immediately notify Sloan prior to such disclosure to allow Sloan an opportunity to contest the disclosure, (ii) assert the privileged and confidential nature of the Confidential Information, and (iii) cooperate fully with Sloan in protecting against any such disclosure and/or obtaining a protective order narrowing the scope of such disclosure and/or use of the Confidential Information. In the event such protection is not obtained, You shall disclose the Confidential Information only to the extent necessary to comply with the applicable legal requirements.</li>
                  <li>For U.S. Government End Users.</li>
                  <p>The Product Software is a <q>commercial item,</q>? as that term is defined at 48 C.F.R. 2.101 (OCT 1995), and more specifically is <q>commercial computer software</q>? and <q>commercial computer software documentation,</q>? as such terms are used in 48 C.F.R. 12.212 (SEPT 1995). Consistent with 48 C.F.R. 12.212 and 48 C.F.R. 227.7202-1 through 227.7202-4 (JUNE 1995), the Product Software is provided to U.S. Government End Users only as a commercial end item and with only those rights as are granted to all other customers pursuant to the terms and conditions herein.</p>
                  <li>Export Compliance.</li>
                  <p>The Product Software and related technology are subject to U.S. export control laws and may be subject to export or import regulations in other countries. You will strictly comply with all such laws and regulations and acknowledge that You have the responsibility to obtain authorization to export, re-export, or import the Product Software and related technology, as may be required. You will indemnify and hold Sloan harmless from any and all claims, losses, liabilities, damages, fines, penalties, costs and expenses (including attorney’s fees) arising from or relating to any breach by You of Your obligations under this section.</p>
                  <li>Governing Law; Venue.</li>
                  <p>The courts in some countries will not apply Illinois law to some types of disputes. If You reside in one of those countries, then where Illinois law is excluded from applying, Your country’s laws will apply to such disputes related to these terms. Otherwise, You agree that these Terms of Use, and any claim, dispute, action, cause of action, issue, or request for relief relating to these Terms of Use, will be governed by the laws of Illinois, without giving effect to any conflicts of laws principles that require the application of the laws of a different jurisdiction. Any action or proceeding relating to these Terms of Use must be brought in a federal or state court located in Cook County, Illinois and each party irrevocably submits to the jurisdiction and venue of any such court in any such claim or dispute, except that Sloan may seek injunctive relief in any court having jurisdiction to protect its intellectual property or Confidential Information.</p>
                  <li>Assignment.</li>
                  <p>Neither the rights nor the obligations arising under these Terms of Use are assignable or delegable by You, and any such attempted assignment shall be void and without effect.</p>
                  <li>Notices.</li>
                  <p>Any notice to You may be provided by email to the email address or text message to the phone that You registered with Sloan.</p>
                  <li>Severability.</li>
                  <p>If any provision of these Terms of Use are unenforceable, such provision will be changed and interpreted to accomplish the objectives of such provision to the greatest extent possible under applicable law and the remaining provisions will continue in full force and effect.</p>
                  <li>Waiver.</li>
                  <p>All waivers by Sloan will be effective only if in writing. Any waiver or failure by Sloan to enforce any provision of these Terms of Use on one occasion will not be deemed a waiver of any other provision or of such provision on any other occasion.</p>
                  <li>General.</li>
                  <p>The Product Software is deemed irrevocably accepted upon the earlier of Your registration or use of the Product Software or Product. Sloan will have no responsibility to provide maintenance or support services with respect to the Product Software.</p>
                  <p>You acknowledge that the Product Software contains valuable trade secrets and proprietary information of Sloan, that any actual or threatened breach of Section 2 (Restrictions) of these Terms of Use will constitute immediate, irreparable harm to Sloan for which monetary damages would be an inadequate remedy, and that injunctive relief is an appropriate remedy for such breach.</p>
              </ol>
  
              <p>The headings of Sections of these Terms of Use are for convenience and are not to be used in interpreting these Terms of Use.</p>
              <p>Except as otherwise provided in this section, no amendment to these Terms of Use will be valid unless it is in writing hand-signed by You and Sloan.</p>
              <p>Questions or Additional Information. If You have questions regarding these Terms of Use, please contact Sloan at <a href="mailto:customer.service@sloan.com?subject=Sloan%20Connect%20App">customer.service@sloan.com</a>.</p>
              <footer><i>Revision 2018-07-26.eula.01</i></footer>
          </div>
          
      </body>`,
};
