/**action types for login module */
export const loginActionTypes = {
  LOGIN_REQUEST: 'LOGIN_REQUEST',
  BIOMETRIC_LOGIN_REQUEST: 'BIOMETRIC_LOGIN_REQUEST',
  LOGIN_FAILURE: 'LOGIN_FAILURE',
  LOGIN_SUCCESS: 'LOGIN_SUCCESS',
  LOGIN_RESET_DATA: 'LOGIN_RESET_DATA',
};

/**action types for deviceSettings module */
export const deviceSettingsActionTypes = {
  DEVICE_SETTINGS_REQUEST: 'DEVICE_SETTINGS_REQUEST',
  DEVICE_SETTINGS_FAILURE: 'DEVICE_SETTINGS_FAILURE',
  DEVICE_SETTINGS_SUCCESS: 'DEVICE_SETTINGS_SUCCESS',
  DEVICE_SETTINGS_RESET_DATA: 'DEVICE_SETTINGS_RESET_DATA',
};

/**action types for login module */
export const otpActionTypes = {
  OTP_REQUEST: 'OTP_REQUEST',
  OTP_FAILURE: 'OTP_FAILURE',
  OTP_SUCCESS: 'OTP_SUCCESS',
  OTP_RESET_DATA: 'OTP_RESET_DATA',
};

/**action types for login module */
export const verifyOtpActionTypes = {
  VERIFY_OTP_REQUEST: 'VERIFY_OTP_REQUEST',
  VERIFY_OTP_FAILURE: 'VERIFY_OTP_FAILURE',
  VERIFY_OTP_SUCCESS: 'VERIFY_OTP_SUCCESS',
  VERIFY_OTP_RESET_DATA: 'VERIFY_OTP_RESET_DATA',
};

/**action types for login module */
export const verifyEmailActionTypes = {
  VERIFY_EMAIL_REQUEST: 'VERIFY_EMAIL_REQUEST',
  VERIFY_EMAIL_FAILURE: 'VERIFY_EMAIL_FAILURE',
  VERIFY_EMAIL_SUCCESS: 'VERIFY_EMAIL_SUCCESS',
  VERIFY_EMAIL_RESET_DATA: 'VERIFY_EMAIL_RESET_DATA',
};

/**action types for signup module */
export const signupActionTypes = {
  SIGNUP_REQUEST: 'SIGNUP_REQUEST',
  SIGNUP_FAILURE: 'SIGNUP_FAILURE',
  SIGNUP_SUCCESS: 'SIGNUP_SUCCESS',
  SIGNUP_RESET_DATA: 'SIGNUP_RESET_DATA',
};

/**action types for forgot password module */
export const forgotPasswordActionTypes = {
  FORGOT_PASSWORD_REQUEST: 'FORGOT_PASSWORD_REQUEST',
  FORGOT_PASSWORD_FAILURE: 'FORGOT_PASSWORD_FAILURE',
  FORGOT_PASSWORD_SUCCESS: 'FORGOT_PASSWORD_SUCCESS',
  FORGOT_PASSWORD_RESET_DATA: 'FORGOT_PASSWORD_RESET_DATA',
};

/**action types for reset password module */
export const resetPasswordActionTypes = {
  RESET_PASSWORD_REQUEST: 'RESET_PASSWORD_REQUEST',
  RESET_PASSWORD_FAILURE: 'RESET_PASSWORD_FAILURE',
  RESET_PASSWORD_SUCCESS: 'RESET_PASSWORD_SUCCESS',
  RESET_PASSWORD_RESET_DATA: 'RESET_PASSWORD_RESET_DATA',
};

/**action types for notification module */
export const notificationActionTypes = {
  NOTIFICATION_REQUEST: 'NOTIFICATION_REQUEST',
  NOTIFICATION_FAILURE: 'NOTIFICATION_FAILURE',
  NOTIFICATION_SUCCESS: 'NOTIFICATION_SUCCESS',
  NOTIFICATION_DATA_SUCCESS: 'NOTIFICATION_DATA_SUCCESS',
  NOTIFICATION_RESET_DATA: 'NOTIFICATION_RESET_DATA',
};

/**action types for notification permission module */
export const notificationPermissionActionTypes = {
  NOTIFICATION_PERMISSION_REQUEST: 'NOTIFICATION_PERMISSION_REQUEST',
  NOTIFICATION_PERMISSION_FAILURE: 'NOTIFICATION_PERMISSION_FAILURE',
  NOTIFICATION_PERMISSION_SUCCESS: 'NOTIFICATION_PERMISSION_SUCCESS',
  NOTIFICATION_PERMISSION_RESET_DATA: 'NOTIFICATION_PERMISSION_RESET_DATA',
};

/**action types for settings module */
export const settingsActionTypes = {
  SETTINGS_REQUEST: 'SETTINGS_REQUEST',
  SETTINGS_FAILURE: 'SETTINGS_FAILURE',
  SETTINGS_SUCCESS: 'SETTINGS_SUCCESS',
  SETTINGS_RESET_DATA: 'SETTINGS_RESET_DATA',
};
