import {EULA_HTML as EULA_HTML_EN} from './en/EULA_HTML';
import {EULA_HTML as EULA_HTML_FR} from './fr/EULA_HTML';
import {EULA_HTML as EULA_HTML_ES} from './es/EULA_HTML';

import {FAQS_HTML as FAQS_HTML_EN} from './en/FAQS_HTML';
import {FAQS_HTML as FAQS_HTML_FR} from './fr/FAQS_HTML';
import {FAQS_HTML as FAQS_HTML_ES} from './es/FAQS_HTML';

import {TROUBLESHOOTING_HTML as TROUBLESHOOTING_HTML_EN} from './en/TROUBLESHOOTING_HTML';
import {TROUBLESHOOTING_HTML as TROUBLESHOOTING_HTML_FR} from './fr/TROUBLESHOOTING_HTML';
import {TROUBLESHOOTING_HTML as TROUBLESHOOTING_HTML_ES} from './es/TROUBLESHOOTING_HTML';

export const EULA_HTML = {
  en: EULA_HTML_EN,
  fr: EULA_HTML_FR,
  es: EULA_HTML_ES,
};

export const FAQS_HTML = {
  en: FAQS_HTML_EN,
  fr: FAQS_HTML_FR,
  es: FAQS_HTML_ES,
};

export const TROUBLESHOOTING_HTML = {
  en: TROUBLESHOOTING_HTML_EN,
  fr: TROUBLESHOOTING_HTML_FR,
  es: TROUBLESHOOTING_HTML_ES,
};
